import { Phase } from "../../../@types/bible";

export const CANON_DATA: Phase[] = [
  {
    id: "f1",
    num: "1",
    title: "CRIAÇÃO & ORIGENS",
    theme: "genesis",
    books: [
      {
        id: "b1",
        num: "1",
        name: "Gênesis 1–5",
        sub: "Criação, Adão e Eva, Caim e Abel, genealogia",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b2",
        num: "2",
        name: "Adão e Eva I",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b3",
        num: "3",
        name: "Adão e Eva II",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b4",
        num: "4",
        name: "Adão e Eva III",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b5",
        num: "5",
        name: "Vida Adae et Evae",
        sub: "Versão latina",
        tags: ["b201"],
      },
      {
        id: "b6",
        num: "6",
        name: "Eslavo Vita Adae et Evae",
        sub: "Versão eslava",
        tags: ["b201"],
      },
      {
        id: "b7",
        num: "7",
        name: "Apocalipse de Adão",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b8",
        num: "8",
        name: "Gênesis 6–11",
        sub: "Vigilantes, Noé, Dilúvio, Torre de Babel",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b9",
        num: "9",
        name: "Narração do Dilúvio — Epopéia de Gilgamesh",
        sub: "Paralelo mesopotâmico ao dilúvio bíblico",
        tags: ["v1"],
      },
      {
        id: "b10",
        num: "10",
        name: "1 Enoch",
        sub: "Vigilantes, Parábolas, Astronomia, Sonhos, Epístola",
        tags: ["b201", "v1"],
      },
      {
        id: "b11",
        num: "11",
        name: "2 Enoch",
        sub: "",
        tags: ["b201", "v1"],
      },
      { id: "b12", num: "12", name: "3 Enoch", sub: "", tags: ["b201"] },
      {
        id: "b12b",
        num: "12b",
        name: " O Livro dos Segredos de Enoque (V1)",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b13",
        num: "13",
        name: "O Livro dos Gigantes",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f2",
    num: "2",
    title: "PATRIARCAS & JUBILEUS",
    theme: "patriarchs",
    books: [
      {
        id: "b14",
        num: "14",
        name: "Gênesis 12–25",
        sub: "Abraão, Ló, Isaque, aliança",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b15",
        num: "15",
        name: "Jubileus",
        sub: "Reescrita do Gênesis com calendário e anjos",
        tags: ["b201", "v1"],
      },

      {
        id: "b16",
        num: "16",
        name: "Testamento de Abraão",
        sub: "A morte e o julgamento da alma do patriarca",
        tags: ["b201", "v1"],
      },
      {
        id: "b17",
        num: "17",
        name: "Apocalipse de Abraão",
        sub: "Visão celestial e conversão",
        tags: ["v1"],
      },
      {
        id: "b18",
        num: "18",
        name: "Livro de Abraão",
        sub: "Versão expandida das tradições abraâmicas",
        tags: ["v3"],
      },
      {
        id: "b19",
        num: "19",
        name: "Caverna dos Tesouros",
        sub: "Tradição siríaca das histórias patriarcais (V1)",
        tags: ["v1"],
      },
      {
        id: "b20",
        num: "20",
        name: "Conto dos Patriarcas",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b21",
        num: "21",
        name: "Gênesis 26–36",
        sub: "Isaque, Jacó, Esaú",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b22",
        num: "22",
        name: "Testamentos Finais dos 12 Patriarcas (Tradição Posterior)",
        sub: "Introdução às últimas palavras dos filhos de Jacó",
        tags: ["b201", "v1"],
      },
      {
        id: "b23",
        num: "23",
        name: "Testamento de Rúben",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b24",
        num: "24",
        name: "Testamento de Simeão",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b25",
        num: "25",
        name: "Testamento de Levi",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b26",
        num: "26",
        name: "Testamento de Judá",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b27",
        num: "27",
        name: "Testamento de Issacar",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b28",
        num: "28",
        name: "Testamento de Zebulom",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b29",
        num: "29",
        name: "Testamento de Dan",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b30",
        num: "30",
        name: "Testamento de Naftali",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b31",
        num: "31",
        name: "Testamento de Gad",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b32",
        num: "32",
        name: "Testamento de Aser",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b33",
        num: "33",
        name: "Testamento de José",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b34",
        num: "34",
        name: "Testamento de Benjamin",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b35",
        num: "35",
        name: "Gênesis 37–50",
        sub: "José no Egito",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b36",
        num: "36",
        name: "José e Asenath",
        sub: "Novela sobre o casamento de José",
        tags: ["v1"],
      },
      {
        id: "b37",
        num: "37",
        name: "Livro de Jasher",
        sub: "Mencionado em Josué e 2 Samuel",
        tags: ["v2"],
      },
    ],
  },
  {
    id: "f3",
    num: "3",
    title: "ÊXODO & A LEI",
    theme: "exodus",
    books: [
      {
        id: "b38",
        num: "38",
        name: "Êxodo",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b39",
        num: "39",
        name: "Janes e Jambres",
        sub: "Os magos do Faraó",
        tags: ["b201"],
      },
      {
        id: "b40",
        num: "40",
        name: "Levítico",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b41",
        num: "41",
        name: "Números",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b42",
        num: "42",
        name: "Deuteronômio",
        sub: "O Shemá e a síntese da Lei",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b43",
        num: "43",
        name: "Testamento de Moisés",
        sub: "Assunção de Moisés (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b44",
        num: "44",
        name: "Apocalipse de Moisés",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b45",
        num: "45",
        name: "Seleções do Livro de Moisés",
        sub: "Trad. Intertestamental (V3)",
        tags: ["v3"],
      },
      {
        id: "b46",
        num: "46",
        name: "Fragmentos de uma Obra Zadoquita",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b47",
        num: "47",
        name: "Documento de Damasco",
        sub: "Manuscritos do Mar Morto",
        tags: ["v3"],
      },
    ],
  },
  {
    id: "f4",
    num: "4",
    title: "CONQUISTA & JUÍZES",
    theme: "conquest_and_judges",
    books: [
      {
        id: "b48",
        num: "48",
        name: "Josué",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b49",
        num: "49",
        name: "Juízes",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b50",
        num: "50",
        name: "Rute",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b51",
        num: "51",
        name: "A História de Ahikar",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b52",
        num: "52",
        name: "Eldad e Modad",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b53",
        num: "53",
        name: "Melchizedek",
        sub: "Sacerdote-rei de Salém",
        tags: ["v1"],
      },
    ],
  },
  {
    id: "f5",
    num: "5",
    title: "REINO DE ISRAEL & TRADIÇÕES ATRIBUÍDAS",
    theme: "kingdom",
    books: [
      {
        id: "b54",
        num: "54",
        name: "1 Samuel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b55",
        num: "55",
        name: "2 Samuel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b56",
        num: "56",
        name: "1 Reis",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b57",
        num: "57",
        name: "2 Reis",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b58",
        num: "58",
        name: "1 Crônicas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b59",
        num: "59",
        name: "2 Crônicas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b60",
        num: "60",
        name: "Testamento de Salomão",
        sub: "Sobre demônios e o Templo",
        tags: ["missing"],
      },
    ],
  },
  {
    id: "f6",
    num: "6",
    title: "EXÍLIO, RETORNO & DEUTEROCANÔNICOS",
    theme: "exile",
    books: [
      {
        id: "b61",
        num: "61",
        name: "1 Esdras",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      { id: "b62", num: "62", name: "2 Esdras", sub: "", tags: ["b201"] },
      {
        id: "b63",
        num: "63",
        name: "4 Esdras (Revelação)",
        sub: "Palavras e revelações de Esdras o santo profeta (V3)",
        tags: ["v3"],
      },
      {
        id: "b64",
        num: "64",
        name: "Neemias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b65",
        num: "65",
        name: "Carta de Aristeias",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b66",
        num: "66",
        name: "Tobias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b67",
        num: "67",
        name: "Judite",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b68",
        num: "68",
        name: "Ester + Ester Adicional",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      { id: "b69", num: "69", name: "Susana", sub: "", tags: ["b201"] },
      {
        id: "b70",
        num: "70",
        name: "Bel e o Dragão",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b71",
        num: "71",
        name: "1 Macabeus",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b72",
        num: "72",
        name: "2 Macabeus",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b73",
        num: "73",
        name: "3 Macabeus",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b74",
        num: "74",
        name: "4 Macabeus",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b75",
        num: "75",
        name: "1 Meqabyan",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b76",
        num: "76",
        name: "2 Meqabyan",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b77",
        num: "77",
        name: "3 Meqabyan",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f7",
    num: "7",
    title: "SABEDORIA & POESIA",
    theme: "wisdom",
    books: [
      {
        id: "b78",
        num: "78",
        name: "Jó",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b79",
        num: "79",
        name: "Salmos 1–72",
        sub: "Livros I e II",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b80",
        num: "80",
        name: "Salmos 73–150",
        sub: "Livros III, IV e V",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b81",
        num: "81",
        name: "Salmos de Salomão",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b82",
        num: "82",
        name: "Salmos Adicionais",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b83",
        num: "83",
        name: "Odes de Salomão",
        sub: "",
        tags: ["b201", "v2"],
      },
      {
        id: "b84",
        num: "84",
        name: "O Hino da Pérola",
        sub: "Poema gnóstico (V1)",
        tags: ["v1", "gnose"],
      },
      {
        id: "b85",
        num: "85",
        name: "Provérbios",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b86",
        num: "86",
        name: "Eclesiastes",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b87",
        num: "87",
        name: "Cântico dos Cânticos",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b88",
        num: "88",
        name: "Sirach (Eclesiástico)",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b89",
        num: "89",
        name: "Sobre a Origem do Mundo",
        sub: "Trad. Gnóstica (V1)",
        tags: ["v1", "gnose"],
      },
      {
        id: "b90",
        num: "90",
        name: "As Frases do Sexto",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b91",
        num: "91",
        name: "As Tradições de Matias",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f8",
    num: "8",
    title: "PROFETAS MAIORES",
    theme: "prophets",
    books: [
      {
        id: "b92",
        num: "92",
        name: "Isaías 1–39",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b93",
        num: "93",
        name: "Isaías 40–66",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b94",
        num: "94",
        name: "Ascensão de Isaías",
        sub: "Inclui o Martírio de Isaías (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b95",
        num: "95",
        name: "Jeremias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b96",
        num: "96",
        name: "Carta de Jeremias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b97",
        num: "97",
        name: "Lamentações",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b98",
        num: "98",
        name: "Baruque 1 · 2 · 3",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b99",
        num: "99",
        name: "Oração de Azarias",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b100",
        num: "100",
        name: "Ezequiel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b101",
        num: "101",
        name: "Daniel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
    ],
  },
  {
    id: "f9",
    num: "9",
    title: "PROFETAS MENORES & ORÁCULOS",
    theme: "prophets",
    books: [
      {
        id: "b102",
        num: "102",
        name: "Oséias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b103",
        num: "103",
        name: "Joel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b104",
        num: "104",
        name: "Amós",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b105",
        num: "105",
        name: "Obadias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b106",
        num: "106",
        name: "Jonas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b107",
        num: "107",
        name: "Miquéias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b108",
        num: "108",
        name: "Naum",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b109",
        num: "109",
        name: "Habacuque",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b110",
        num: "110",
        name: "Sofonias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b111",
        num: "111",
        name: "Ageu",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b112",
        num: "112",
        name: "Zacarias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b113",
        num: "113",
        name: "Malaquias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b114",
        num: "114",
        name: "Oração de Manassés",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b115",
        num: "115",
        name: "Oráculos Sibilinos I–XIV",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f10",
    num: "10",
    title: "ENTRE OS TESTAMENTOS",
    theme: "intertestamental",
    div: "PERÍODO INTERTESTAMENTAL",
    books: [
      {
        id: "b116",
        num: "116",
        name: "A Ascensão de Isaías (Revisão)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b117",
        num: "117",
        name: "Testamento de Moisés (Revisão)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b118",
        num: "118",
        name: "Livro de Adão (V.3)",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b119",
        num: "119",
        name: "Testamento de Isaac",
        sub: "Tradição patriarcal intertestamental",
        tags: ["v1"],
      },
      {
        id: "b120",
        num: "120",
        name: "Testamento de Jacó",
        sub: "Tradição patriarcal intertestamental",
        tags: ["v1"],
      },
    ],
  },
  {
    id: "f11",
    num: "11",
    title: "INFÂNCIA DE JESUS",
    theme: "infancy",
    div: "NOVO TESTAMENTO & APÓCRIFOS CRISTÃOS",
    books: [
      {
        id: "b121",
        num: "121",
        name: "Protevangelico",
        sub: "Proto Evangelho de Tiago (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b122",
        num: "122",
        name: "Evangelho da Natividade de Maria",
        sub: "Evangelho do nascimento de Maria (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b123",
        num: "123",
        name: "Pseudo-Mateus",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b124",
        num: "124",
        name: "Evangelho da Infância de Tomé",
        sub: "Infância de Jesus / Salvador / Pseudo Tomé (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b125",
        num: "125",
        name: "Fragmentos de Tomé",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b126",
        num: "126",
        name: "Evangelho Árabe da Infância",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b127",
        num: "127",
        name: "Evangelho Armênio da Infância",
        sub: "Excertos do Evangelho Armênio (V1)",
        tags: ["v1"],
      },
      {
        id: "b128",
        num: "128",
        name: "História de José, o Carpinteiro",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b129",
        num: "129",
        name: "Cartas de Herodes e Pilatos",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f12",
    num: "12",
    title: "MINISTÉRIO DE JESUS — OS EVANGELHOS",
    theme: "gospels",
    books: [
      {
        id: "b130",
        num: "130",
        name: "Mateus 1–13",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b131",
        num: "131",
        name: "Mateus 14–28",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b132",
        num: "132",
        name: "Marcos",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b133",
        num: "133",
        name: "Evangelho Secreto de Marcos",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b134",
        num: "134",
        name: "Lucas 1–12",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b135",
        num: "135",
        name: "Lucas 13–24",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b136",
        num: "136",
        name: "João 1–12",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b137",
        num: "137",
        name: "João 13–21",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b138",
        num: "138",
        name: "Narrativa da Paixão Pré-Markan",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b139",
        num: "139",
        name: "Epístolas de Jesus e Abgarus",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b140",
        num: "140",
        name: "Evangelho dos Hebreus",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b141",
        num: "141",
        name: "Evangelho dos Ebionitas",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b142",
        num: "142",
        name: "Evangelho dos Nazarenos",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b143",
        num: "143",
        name: "Evangelho de Egerton",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b144",
        num: "144",
        name: "Evangelho de Oxirrinco",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b145",
        num: "145",
        name: "Diálogo do Salvador",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b146",
        num: "146",
        name: "Evangelho Segundo Pedro",
        sub: "Evangelho de Pedro (V1/V2)",
        tags: ["b201", "v1", "v2"],
      },
      {
        id: "b147",
        num: "147",
        name: "A Vingança do Salvador",
        sub: "",
        tags: ["b201", "v1"],
      },
    ],
  },
  {
    id: "f12b",
    num: "12b",
    title: "CICLO DE PILATOS & PÓS-RESSURREIÇÃO",
    theme: "passion",
    books: [
      {
        id: "b148",
        num: "148",
        name: "Evangelho de Nicodemus",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b149",
        num: "149",
        name: "Descida ao Inferno (Grego)",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b150",
        num: "150",
        name: "Descida ao Inferno (Latim)",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b151",
        num: "151",
        name: "Ciclo de Pilatos",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b152",
        num: "152",
        name: "Condenação de Pilatos",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b153",
        num: "153",
        name: "Cartas do Senhor",
        sub: "Carta do Senhor (V1)",
        tags: ["v1"],
      },
      {
        id: "b154",
        num: "154",
        name: "Declarações de José de Arimatéia",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b155",
        num: "155",
        name: "A Narrativa de José de Arimatéia",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b156",
        num: "156",
        name: "Discurso Sobre o Domingo",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b157",
        num: "157",
        name: "Apócrifos da Assunção",
        sub: "Trad. da Assunção (V1)",
        tags: ["v1"],
      },
      {
        id: "b158",
        num: "158",
        name: "Passagem da Virgem Maria",
        sub: "Passagem da Bem-Aventurada (V1)",
        tags: ["v1"],
      },
      {
        id: "b159",
        num: "159",
        name: "Agrapha Extra-Evangelho",
        sub: "Ditos não canônicos de Jesus (V1)",
        tags: ["v1"],
      },
      {
        id: "b160",
        num: "160",
        name: "Ressurreição de Cristo (Bartolomeu)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b161",
        num: "161",
        name: "Evangelho de Bartolomeu",
        sub: "",
        tags: ["b201", "v1"],
      },
    ],
  },
  {
    id: "f13",
    num: "13",
    title: "ATOS & MISSÃO APOSTÓLICA",
    theme: "acts",
    books: [
      {
        id: "b162",
        num: "162",
        name: "Atos 1–12",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b163",
        num: "163",
        name: "Atos 13–28",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b164",
        num: "164",
        name: "Atos 29 (Apócrifo)",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b165",
        num: "165",
        name: "Atos de Pedro e os 12",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b166",
        num: "166",
        name: "Atos de Pedro",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b167",
        num: "167",
        name: "Atos de Pedro e André",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b168",
        num: "168",
        name: "Atos de Pedro e Paulo",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b169",
        num: "169",
        name: "Atos de Paulo e Tecla",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b170",
        num: "170",
        name: "Atos de André",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b171",
        num: "171",
        name: "Atos de André e Matias",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b172",
        num: "172",
        name: "Atos de João",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b173",
        num: "173",
        name: "Atos de Tomé",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b174",
        num: "174",
        name: "Consumação de Tomé",
        sub: "A consumação do apóstolo Tomé (V3)",
        tags: ["v3"],
      },
      {
        id: "b175",
        num: "175",
        name: "Atos de Barnabé",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b176",
        num: "176",
        name: "Atos e Martírio de São Mateus",
        sub: "Atos e Martírio do Apóstolo (V3)",
        tags: ["v3"],
      },
      {
        id: "b177",
        num: "177",
        name: "Martírio de Mateus",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b178",
        num: "178",
        name: "Vida das Santas Mulheres",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b179",
        num: "179",
        name: "Atos do Santo Apóstolo",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b180",
        num: "180",
        name: "Ensino de Tadeu",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b181",
        num: "181",
        name: "Livro de João Evangelista",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b182",
        num: "182",
        name: "Atos de Perpétua e Felicidade",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b183",
        num: "183",
        name: "A Pregação de Pedro",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f14",
    num: "14",
    title: "CARTAS DE PAULO",
    theme: "epistles",
    books: [
      {
        id: "b184",
        num: "184",
        name: "Gálatas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b185",
        num: "185",
        name: "1 Tessalonicenses",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b186",
        num: "186",
        name: "2 Tessalonicenses",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b187",
        num: "187",
        name: "1 Coríntios",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b188",
        num: "188",
        name: "2 Coríntios",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b189",
        num: "189",
        name: "III Coríntios",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b190",
        num: "190",
        name: "Romanos",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b191",
        num: "191",
        name: "Filipenses",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b192",
        num: "192",
        name: "Colossenses",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b193",
        num: "193",
        name: "Filemão",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b194",
        num: "194",
        name: "Efésios",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b195",
        num: "195",
        name: "1 Timóteo",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b196",
        num: "196",
        name: "2 Timóteo",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b197",
        num: "197",
        name: "Tito",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b198",
        num: "198",
        name: "Hebreus",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b199",
        num: "199",
        name: "Laodicenses",
        sub: "Epístola aos Laodicenses (V3)",
        tags: ["b201", "v3"],
      },
      {
        id: "b200",
        num: "200",
        name: "Epístolas a Sêneca",
        sub: "Correspondência entre Paulo e Sêneca (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b201",
        num: "201",
        name: "Prece de Paulo",
        sub: "",
        tags: ["v3"],
      },
    ],
  },
  {
    id: "f15",
    num: "15",
    title: "CARTAS GERAIS, APOCALIPSES & REVELAÇÃO",
    theme: "apocalypse",
    books: [
      {
        id: "b202",
        num: "202",
        name: "Tiago",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b203",
        num: "203",
        name: "1 Pedro",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b204",
        num: "204",
        name: "2 Pedro",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b205",
        num: "205",
        name: "1 João",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b206",
        num: "206",
        name: "2 João",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b207",
        num: "207",
        name: "3 João",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b208",
        num: "208",
        name: "Judas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b209",
        num: "209",
        name: "Epístola dos Apóstolos",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b210",
        num: "210",
        name: "Carta de Pedro à Felipe",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b211",
        num: "211",
        name: "Epístola de Barnabé",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b212",
        num: "212",
        name: "Revelação (Apocalipse) 1–11",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b213",
        num: "213",
        name: "Revelação 12–22",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b214",
        num: "214",
        name: "João o Teólogo",
        sub: "A Revelação de São João, o Teólogo (V3)",
        tags: ["v3"],
      },
      {
        id: "b215",
        num: "215",
        name: "Apocalipse de Pedro",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b216",
        num: "216",
        name: "Apocalipse de Paulo",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b217",
        num: "217",
        name: "Apocalipse de Baruch",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b218",
        num: "218",
        name: "Apocalipse de Elias",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b219",
        num: "219",
        name: "Apocalipse de Tomé",
        sub: "Revelação de Tomé (V1)",
        tags: ["v1"],
      },
    ],
  },
  {
    id: "f16",
    num: "16",
    title: "PAIS DA IGREJA & TEXTOS APOSTÓLICOS",
    theme: "fathers",
    books: [
      {
        id: "b220",
        num: "220",
        name: "O Didachê",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b221",
        num: "221",
        name: "Pastor de Hermas",
        sub: "Livros I (Visões), II (Mandatos) e III (Similitudes) (V2)",
        tags: ["v2"],
      },
      {
        id: "b222",
        num: "222",
        name: "1 Clemente",
        sub: "Primeira Epístola de Clemente aos Coríntios (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b223",
        num: "223",
        name: "2 Clemente",
        sub: "Segunda Epístola de Clemente aos Coríntios (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b224",
        num: "224",
        name: "Apócrifo de Tiago",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b225",
        num: "225",
        name: "Inácio de Antioquia",
        sub: "Efésios, Magnésios, Trales, Romanos, Filadelfianos, Esmirniotas e Policarpo (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b226",
        num: "226",
        name: "Policarpo aos Filipenses",
        sub: "Epístola de Policarpo aos Filipenses (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b227",
        num: "227",
        name: "Martírio de Inácio",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b228",
        num: "228",
        name: "Martírio de Policarpo",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b229",
        num: "229",
        name: "Tertuliano (Mártires)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b230",
        num: "230",
        name: "Carta de Pilatos",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b231",
        num: "231",
        name: "Oração Ação de Graças",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b232",
        num: "232",
        name: "Epifânio sobre a Justiça",
        sub: "",
        tags: ["b201"],
      },
      { id: "b233", num: "233", name: "Credos", sub: "", tags: ["b201"] },
    ],
  },
  {
    id: "f17",
    num: "17",
    title: "GNOSE & TEXTOS ESOTÉRICOS",
    theme: "gnosis",
    div: "TEXTOS GNÓSTICOS",
    books: [
      {
        id: "b234",
        num: "234",
        name: "Evangelho de Tomé",
        sub: "Evangelho Segundo Tomé, o Dídimo (V1)",
        tags: ["b201", "v1", "gnose"],
      },
      {
        id: "b235",
        num: "235",
        name: "Fragmentos Gregos de Tomé",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b236",
        num: "236",
        name: "Evangelho de Filipe",
        sub: "Evangelho Segundo Felipe (V1)",
        tags: ["b201", "v1", "gnose"],
      },
      {
        id: "b237",
        num: "237",
        name: "Maria Madalena",
        sub: "Excertos do Evangelho de Maria (V1)",
        tags: ["v1", "gnose"],
      },
      {
        id: "b238",
        num: "238",
        name: "Evangelho de Judas",
        sub: "",
        tags: ["v1", "gnose"],
      },
      {
        id: "b239",
        num: "239",
        name: "Evangelho de Valentino",
        sub: "",
        tags: ["v1", "gnose"],
      },
      {
        id: "b240",
        num: "240",
        name: "Evangelho da Verdade",
        sub: "",
        tags: ["b201", "v1", "gnose"],
      },
      {
        id: "b241",
        num: "241",
        name: "Evangelho dos Egípcios",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b242",
        num: "242",
        name: "Apócrifo de João",
        sub: "",
        tags: ["b201", "v3", "gnose"],
      },
      {
        id: "b243",
        num: "243",
        name: "Thomas Contendor",
        sub: "Livro de Tomé o Contendor (V3)",
        tags: ["b201", "v3", "gnose"],
      },
      {
        id: "b244",
        num: "244",
        name: "Tratado Grande Seth",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b245",
        num: "245",
        name: "Basilides",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b246",
        num: "246",
        name: "Livro de Marcião",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b247",
        num: "247",
        name: "Livro de Sindos",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b248",
        num: "248",
        name: "Fonte Q",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b249",
        num: "249",
        name: "Pistis Sophia",
        sub: "",
        tags: ["missing", "gnose"],
      },
      {
        id: "b250",
        num: "250",
        name: "Evangelho Nestoriano",
        sub: "",
        tags: ["missing"],
      },
    ],
  },
  {
    id: "f18",
    num: "18",
    title: "GNOSE COMO PONTE",
    theme: "bridge",
    div: "TRANSIÇÃO ISLÃ",
    books: [
      {
        id: "b251",
        num: "251",
        name: "Escrituras Setianas",
        sub: "",
        tags: ["gnose", "ponte", "missing"],
      },
      {
        id: "b252",
        num: "252",
        name: "Ele Não Morreu na Cruz",
        sub: "",
        tags: ["ponte", "missing"],
      },
      {
        id: "b253",
        num: "253",
        name: "O Famigerado Paulo",
        sub: "",
        tags: ["ponte", "missing"],
      },
      {
        id: "b254",
        num: "254",
        name: "EUTAOGNOSE",
        sub: "",
        tags: ["ponte", "missing"],
      },
    ],
  },
  {
    id: "f19",
    num: "19",
    title: "ÚLTIMA LEITURA",
    theme: "islam",
    books: [
      {
        id: "b255",
        num: "255",
        name: "Evangelho de Barnabé",
        sub: "",
        tags: ["missing", "ponte"],
      },
      {
        id: "bQ",
        num: "→",
        name: "✦ O ALCORÃO ✦",
        sub: "",
        tags: [],
        isQ: true,
      },
    ],
  },
];
