import { Phase } from "../../../@types/bible";

export const CANON_DATA: Phase[] = [
  {
    id: "f0",
    num: "0",
    title: "FUNDAMENTOS & CHAVES HERMÉTICAS",
    theme: "hermetism_base",
    div: "ESTUDOS PRELIMINARES — CHAVES DE LEITURA",
    books: [
      {
        id: "b0_1",
        num: "0a",
        name: "Corpus Hermeticum Græcum",
        sub: "Trad. David Pessoa de Lira — Filosofia da origem da consciência e do Verbo",
        tags: ["hermetismo", "base", "carrinho"],
      },
      {
        id: "b0_2",
        num: "0b",
        name: "A Tábua De Esmeralda",
        sub: "Trad. Fabio R. de Araujo — As leis secretas da analogia e correspondência",
        tags: ["alquimia", "base", "carrinho"],
      },
      {
        id: "b0_3",
        num: "0c",
        name: "História da Magia",
        sub: "Éliphas Lévi — Panorama histórico da evolução do pensamento oculto na humanidade",
        tags: ["ocultismo", "historia", "carrinho"],
      },
      {
        id: "b0_4",
        num: "0d",
        name: "A Cabala: Tradição Secreta do Ocidente",
        sub: "Papus — A estrutura teórica e cosmogônica da Árvore da Vida",
        tags: ["cabala", "base", "carrinho"],
      },
      {
        id: "b0_5",
        num: "0e",
        name: "Dogma e Ritual da Alta Magia",
        sub: "Éliphas Lévi — O compêndio absoluto das correspondências e das leis da vontade aplicada",
        tags: ["ocultismo", "teoria", "carrinho"],
      },
      {
        id: "b0_6",
        num: "0f",
        name: "A Chave dos Grandes Mistérios",
        sub: "Éliphas Lévi — Chaves simbólicas e a reconciliação entre ciência e religião",
        tags: ["ocultismo", "teoria", "carrinho"],
      },
      {
        id: "b0_7",
        num: "0g",
        name: "Introdução à Ciência Hermética",
        sub: "Giuliano Kremmerz — O caminho iniciático e as leis da magia natural",
        tags: ["hermetismo", "pratica", "carrinho"],
      },
      {
        id: "b0_8",
        num: "0h",
        name: "O Caibalion",
        sub: "Três Iniciados — Os sete princípios herméticos que regem a verdade oculta e as leis da mente",
        tags: ["hermetismo", "base", "carrinho"],
      },
    ],
  },
  {
    id: "f1",
    num: "1",
    title: "CRIAÇÃO & ORIGENS",
    theme: "genesis",
    books: [
      {
        id: "b1",
        num: "1",
        name: "Gênesis 1–5",
        sub: "Criação, Adão e Eva, Caim e Abel, genealogia",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b1_comp",
        num: "1b",
        name: "Demiurgos: Sobre a Criação de Mundos",
        sub: "Juliano C. S. Neves — O contraponto filosófico e gnótico do processo de criação material",
        tags: ["gnose", "cosmogonia", "carrinho"],
      },
      {
        id: "b2",
        num: "2",
        name: "Adão e Eva I",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b3",
        num: "3",
        name: "Adão e Eva II",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b4",
        num: "4",
        name: "Adão e Eva III",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b5",
        num: "5",
        name: "Vida Adae et Evae",
        sub: "Versão latina",
        tags: ["b201"],
      },
      {
        id: "b6",
        num: "6",
        name: "Eslavo Vita Adae et Evae",
        sub: "Versão eslava",
        tags: ["b201"],
      },
      {
        id: "b7",
        num: "7",
        name: "Livro de Adão",
        sub: "O Conflito de Adão e Eva com Satã (V1)",
        tags: ["v3"],
      },
      {
        id: "b7b",
        num: "7b",
        name: "Testamento de Adão",
        sub: "(V1)",
        tags: ["v3"],
      },
      {
        id: "b7c",
        num: "7c",
        name: "Apocalipse de Adão",
        sub: "Revelação gnóstica de Adão a seu filho Sete",
        tags: ["b201", "v1", "nag hammadi"],
      },
      {
        id: "b8",
        num: "8",
        name: "Gênesis 6–11",
        sub: "Vigilantes, Noé, Dilúvio, Torre de Babel",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b9",
        num: "9",
        name: "Narração do Dilúvio — Epopéia de Gilgamesh",
        sub: "Paralelo mesopotâmico ao dilúvio bíblico",
        tags: ["v1"],
      },
      {
        id: "b10",
        num: "10",
        name: "1 Enoch",
        sub: "Vigilantes, Parábolas, Astronomia, Sonhos, Epístola",
        tags: ["b201", "v1"],
      },
      {
        id: "b11",
        num: "11",
        name: "2 Enoch",
        sub: "",
        tags: ["b201", "v1"],
      },
      { id: "b12", num: "12", name: "3 Enoch", sub: "", tags: ["b201"] },
      {
        id: "b12b",
        num: "12b",
        name: "O Livro dos Segredos de Enoque (V1)",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b13",
        num: "13",
        name: "O Livro dos Gigantes",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f2",
    num: "2",
    title: "PATRIARCAS & JUBILEUS",
    theme: "patriarchs",
    books: [
      {
        id: "b14",
        num: "14",
        name: "Gênesis 12–25",
        sub: "Abraão, Ló, Isaque, aliança",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b14_comp",
        num: "14b",
        name: "Cabala prática sem mistérios",
        sub: "Maggy Whitehouse — Aplicação analítica dos arquétipos dos Patriarcas na Árvore",
        tags: ["cabala", "analise", "carrinho"],
      },
      {
        id: "b15",
        num: "15",
        name: "Jubileus",
        sub: "Reescrita do Gênesis com calendário e anjos",
        tags: ["b201", "v1"],
      },
      {
        id: "b16",
        num: "16",
        name: "Testamento de Abraão",
        sub: "A morte e o julgamento da alma do patriarca",
        tags: ["b201", "v1"],
      },
      {
        id: "b17",
        num: "17",
        name: "Apocalipse de Abraão",
        sub: "Visão celestial e conversão",
        tags: ["v1"],
      },
      {
        id: "b18",
        num: "18",
        name: "Livro de Abraão",
        sub: "Versão expandida das tradições abraâmicas",
        tags: ["v3"],
      },
      {
        id: "b19",
        num: "19",
        name: "Caverna dos Tesouros",
        sub: "Tradição siríaca das histórias patriarcais (V1)",
        tags: ["v1"],
      },
      {
        id: "b20",
        num: "20",
        name: "Conto dos Patriarcas",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b21",
        num: "21",
        name: "Gênesis 26–36",
        sub: "Isaque, Jacó, Esaú",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b22",
        num: "22",
        name: "Testamentos Finais dos 12 Patriarcas (Tradição Posterior)",
        sub: "Introdução às últimas palavras dos filhos de Jacó",
        tags: ["b201", "v1"],
      },
      {
        id: "b23",
        num: "23",
        name: "Testamento de Rúben",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b24",
        num: "24",
        name: "Testamento de Simeão",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b25",
        num: "25",
        name: "Testamento de Levi",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b26",
        num: "26",
        name: "Testamento de Judá",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b27",
        num: "27",
        name: "Testamento de Issacar",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b28",
        num: "28",
        name: "Testamento de Zebulom",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b29",
        num: "29",
        name: "Testamento de Dan",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b30",
        num: "30",
        name: "Testamento de Naftali",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b31",
        num: "31",
        name: "Testamento de Gad",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b32",
        num: "32",
        name: "Testamento de Aser",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b33",
        num: "33",
        name: "Testamento de José",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b34",
        num: "34",
        name: "Testamento de Benjamin",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b35",
        num: "35",
        name: "Gênesis 37–50",
        sub: "José no Egito",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b36",
        num: "36",
        name: "José e Asenath",
        sub: "Novela sobre o casamento de José",
        tags: ["v1"],
      },
      {
        id: "b37",
        num: "37",
        name: "Livro de Jasher",
        sub: "Mencionado em Josué e 2 Samuel",
        tags: ["v2"],
      },
      {
        id: "b38",
        num: "38",
        name: "Escada de Jacó",
        sub: "Expansão do sonho de Jacó em Betel",
        tags: ["missing"],
      },
      {
        id: "b39",
        num: "39",
        name: "Testamento de Jó",
        sub: "Expansão apócrifa da história de Jó",
        tags: ["missing"],
      },
      {
        id: "b40",
        num: "40",
        name: "Pseudo-Filo — Antiguidades Bíblicas",
        sub: "Reescrita de Adão a Saul",
        tags: ["missing"],
      },
    ],
  },
  {
    id: "f3",
    num: "3",
    title: "ÊXODO & A LEI",
    theme: "exodus",
    books: [
      { id: "b41", num: "41", name: "Êxodo", sub: "", tags: ["b201", "cnbb"] },
      {
        id: "b42",
        num: "42",
        name: "Janes e Jambres",
        sub: "Os magos do Faraó",
        tags: ["b201"],
      },
      {
        id: "b43",
        num: "43",
        name: "Levítico",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b44",
        num: "44",
        name: "Números",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b45",
        num: "45",
        name: "Deuteronômio",
        sub: "O Shemá e a síntese da Lei",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b46",
        num: "46",
        name: "Testamento de Moisés",
        sub: "Assunção de Moisés (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b47",
        num: "47",
        name: "Apocalipse de Moisés",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b48",
        num: "48",
        name: "Seleções do Livro de Moisés",
        sub: "Trad. Intertestamental (V3)",
        tags: ["v3"],
      },
      {
        id: "b49",
        num: "49",
        name: "Fragmentos de uma Obra Zadoquita",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b50",
        num: "50",
        name: "Documento de Damasco",
        sub: "Manuscritos do Mar Morto",
        tags: ["v3"],
      },
    ],
  },
  {
    id: "f4",
    num: "4",
    title: "MANUSCRITOS DO MAR MORTO",
    theme: "qumran",
    books: [
      {
        id: "b51",
        num: "51",
        name: "Regra da Comunidade (1QS)",
        sub: "Serek ha-Yahad — regras da comunidade de Qumran",
        tags: ["missing"],
      },
      {
        id: "b52",
        num: "52",
        name: "Pergaminho da Guerra (1QM)",
        sub: "Milhamah — guerra dos filhos da luz contra os filhos das trevas",
        tags: ["missing"],
      },
      {
        id: "b53",
        num: "53",
        name: "Hinos de Ação de Graças (1QH)",
        sub: "Hodayot — hinos de agradecimento",
        tags: ["missing"],
      },
      {
        id: "b54",
        num: "54",
        name: "Pergaminho do Templo (11QT)",
        sub: "O maior manuscrito de Qumran — lei e arquitetura do Templo",
        tags: ["missing"],
      },
      {
        id: "b55",
        num: "55",
        name: "Apócrifo de Gênesis (1QapGen)",
        sub: "Expansão narrativa de Gênesis 1–15",
        tags: ["missing"],
      },
    ],
  },
  {
    id: "f5",
    num: "5",
    title: "CONQUISTA & JUÍZES",
    theme: "conquest_and_judges",
    books: [
      { id: "b56", num: "56", name: "Josué", sub: "", tags: ["b201", "cnbb"] },
      { id: "b57", num: "57", name: "Juízes", sub: "", tags: ["b201", "cnbb"] },
      { id: "b58", num: "58", name: "Rute", sub: "", tags: ["b201", "cnbb"] },
      {
        id: "b59",
        num: "59",
        name: "A História de Ahikar",
        sub: "",
        tags: ["b201"],
      },
      { id: "b60", num: "60", name: "Eldad e Modad", sub: "", tags: ["b201"] },
      {
        id: "b61",
        num: "61",
        name: "Melchizedek",
        sub: "Sacerdote-rei de Salém",
        tags: ["v1"],
      },
    ],
  },
  {
    id: "f6",
    num: "6",
    title: "REINO DE ISRAEL & TRADIÇÕES ATRIBUÍDAS",
    theme: "kingdom",
    books: [
      {
        id: "b62",
        num: "62",
        name: "1 Samuel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b63",
        num: "63",
        name: "2 Samuel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      { id: "b64", num: "64", name: "1 Reis", sub: "", tags: ["b201", "cnbb"] },
      { id: "b65", num: "65", name: "2 Reis", sub: "", tags: ["b201", "cnbb"] },
      {
        id: "b66",
        num: "66",
        name: "1 Crônicas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b67",
        num: "67",
        name: "2 Crônicas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b68",
        num: "68",
        name: "Testamento de Salomão",
        sub: "Sobre demônios e o Templo",
        tags: ["missing"],
      },
      {
        id: "b68_grim1",
        num: "68b",
        name: "A clavícula de Salomão",
        sub: "S. L. MacGregor Mathers — Estudo analítico-textual do manual ritualístico medieval atribuído a Salomão",
        tags: ["grimorio", "solomon", "carrinho"],
      },
      {
        id: "b68_grim2",
        num: "68c",
        name: "Goetia",
        sub: "Humberto Maggi — Estudo das chaves de evocação e controle simbólico dos 72 espíritos",
        tags: ["grimorio", "goetia", "carrinho"],
      },
      {
        id: "b68_grim3",
        num: "68d",
        name: "Grimorium Verum",
        sub: "Frater Goya (Anderson Rosa) — Análise técnica das correntes e hierarquias da tradição salomônica",
        tags: ["grimorio", "pratica", "carrinho"],
      },
    ],
  },
  {
    id: "f7",
    num: "7",
    title: "EXÍLIO, RETORNO & DEUTEROCANÔNICOS",
    theme: "exile",
    books: [
      {
        id: "b69",
        num: "69",
        name: "1 Esdras",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      { id: "b70", num: "70", name: "2 Esdras", sub: "", tags: ["b201"] },
      {
        id: "b71",
        num: "71",
        name: "4 Esdras",
        sub: "(Revelação)",
        tags: ["v3"],
      },
      {
        id: "b71b",
        num: "71b",
        name: "Palavra e Revelação de Esdras",
        sub: "O Santo Profeta e Amado de Deus (V3)",
        tags: ["v3"],
      },
      {
        id: "b72",
        num: "72",
        name: "Neemias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b73",
        num: "73",
        name: "Carta de Aristeias",
        sub: "",
        tags: ["v3"],
      },
      { id: "b74", num: "74", name: "Tobias", sub: "", tags: ["b201", "cnbb"] },
      { id: "b75", num: "75", name: "Judite", sub: "", tags: ["b201", "cnbb"] },
      {
        id: "b76",
        num: "76",
        name: "Ester + Ester Adicional",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      { id: "b77", num: "77", name: "Susana", sub: "", tags: ["b201"] },
      { id: "b78", num: "78", name: "Bel e o Dragão", sub: "", tags: ["b201"] },
      {
        id: "b79",
        num: "79",
        name: "1 Macabeus",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b80",
        num: "80",
        name: "2 Macabeus",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b81",
        num: "81",
        name: "3 Macabeus",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b82",
        num: "82",
        name: "4 Macabeus",
        sub: "",
        tags: ["b201", "v3"],
      },
      { id: "b83", num: "83", name: "1 Meqabyan", sub: "", tags: ["b201"] },
      { id: "b84", num: "84", name: "2 Meqabyan", sub: "", tags: ["b201"] },
      { id: "b85", num: "85", name: "3 Meqabyan", sub: "", tags: ["b201"] },
      {
        id: "b86",
        num: "86",
        name: "Sabedoria de Salomão",
        sub: "Sabedoria deuterocanônica atribuída a Salomão",
        tags: ["missing", "cnbb"],
      },
    ],
  },
  {
    id: "f8",
    num: "8",
    title: "SABEDORIA & POESIA",
    theme: "wisdom",
    books: [
      { id: "b87", num: "87", name: "Jó", sub: "", tags: ["b201", "cnbb"] },
      {
        id: "b88",
        num: "88",
        name: "Salmos 1–72",
        sub: "Livros I e II",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b89",
        num: "89",
        name: "Salmos 73–150",
        sub: "Livros III, IV e V",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b89_comp",
        num: "89b",
        name: "O livro dos esplendores",
        sub: "Éliphas Lévi — O mistério hierático e a interpretação cabalística ocidental dos salmos e segredos tradicionais",
        tags: ["cabala", "esoterismo", "carrinho"],
      },
      {
        id: "b90",
        num: "90",
        name: "Salmos de Salomão",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b91",
        num: "91",
        name: "Salmos Adicionais",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b92",
        num: "92",
        name: "Odes de Salomão",
        sub: "",
        tags: ["b201", "v2"],
      },
      {
        id: "b93",
        num: "93",
        name: "O Hino da Pérola",
        sub: "Poema gnóstico sethiano",
        tags: ["v1", "gnose"],
      },
      {
        id: "b94",
        num: "94",
        name: "Provérbios",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b95",
        num: "95",
        name: "Eclesiastes",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b96",
        num: "96",
        name: "Cântico dos Cânticos",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b97",
        num: "97",
        name: "Sirach (Eclesiástico)",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b98",
        num: "98",
        name: "Sobre a Origem do Mundo",
        sub: "Tratado cosmogônico sobre o Caos e o Demiurgo",
        tags: ["v1", "gnose", "nag hammadi"],
      },
      {
        id: "b99",
        num: "99",
        name: "As Frases do Sexto",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b100",
        num: "100",
        name: "As Tradições de Matias",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f9",
    num: "9",
    title: "PROFETAS MAIORES",
    theme: "prophets",
    books: [
      {
        id: "b101",
        num: "101",
        name: "Isaías 1–39",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b102",
        num: "102",
        name: "Isaías 40–66",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b102_comp",
        num: "102b",
        name: "Magus: Tratado Completo de Alquimia e Filosofia Oculta",
        sub: "Francis Barrett — Enciclopédia clássica de síntese; excelente paralelo para o estudo analítico do período profético e astrológico",
        tags: ["ocultismo", "enciclopedia", "carrinho"],
      },
      {
        id: "b103",
        num: "103",
        name: "Ascensão de Isaías",
        sub: "(V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b103b",
        num: "103b",
        name: "Martírio de Isaías",
        sub: "(V1)",
        tags: ["v1"],
      },
      {
        id: "b104",
        num: "104",
        name: "Jeremias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b105",
        num: "105",
        name: "Carta de Jeremias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b106",
        num: "106",
        name: "Lamentações",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b107",
        num: "107",
        name: "Baruque 1 · 2 · 3",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b108",
        num: "108",
        name: "Oração de Azarias",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b109",
        num: "109",
        name: "Ezequiel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b110",
        num: "110",
        name: "Daniel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b111",
        num: "111",
        name: "4 Baruc (Paraleipomena Jeremiou)",
        sub: "Expansão apócrifa de Jeremias e Baruc",
        tags: ["missing"],
      },
      {
        id: "b112",
        num: "112",
        name: "Vida dos Profetas",
        sub: "Tradições biográficas dos profetas do AT",
        tags: ["missing"],
      },
    ],
  },
  {
    id: "f10",
    num: "10",
    title: "PROFETAS MENORES & ORÁCULOS",
    theme: "minor_prophets",
    books: [
      {
        id: "b113",
        num: "113",
        name: "Oséias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      { id: "b114", num: "114", name: "Joel", sub: "", tags: ["b201", "cnbb"] },
      { id: "b115", num: "115", name: "Amós", sub: "", tags: ["b201", "cnbb"] },
      {
        id: "b116",
        num: "116",
        name: "Obadias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b117",
        num: "117",
        name: "Jonas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b118",
        num: "118",
        name: "Miquéias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      { id: "b119", num: "119", name: "Naum", sub: "", tags: ["b201", "cnbb"] },
      {
        id: "b120",
        num: "120",
        name: "Habacuque",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b121",
        num: "121",
        name: "Sofonias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      { id: "b122", num: "122", name: "Ageu", sub: "", tags: ["b201", "cnbb"] },
      {
        id: "b123",
        num: "123",
        name: "Zacarias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b124",
        num: "124",
        name: "Malaquias",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b125",
        num: "125",
        name: "Oração de Manassés",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b126",
        num: "126",
        name: "Oráculos Sibilinos I–XIV",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f11",
    num: "11",
    title: "ENTRE OS TESTAMENTOS",
    theme: "intertestamental",
    div: "PERÍODO INTERTESTAMENTAL",
    books: [
      {
        id: "b127",
        num: "127",
        name: "A Ascensão de Isaías (Revisão)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b128",
        num: "128",
        name: "Testamento de Moisés (Revisão)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b129",
        num: "129",
        name: "Livro de Adão (V.3)",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b130",
        num: "130",
        name: "Testamento de Isaac",
        sub: "Tradição patriarcal intertestamental",
        tags: ["v1"],
      },
      {
        id: "b131",
        num: "131",
        name: "Testamento de Jacó",
        sub: "Tradição patriarcal intertestamental",
        tags: ["v1"],
      },
    ],
  },
  {
    id: "f12",
    num: "12",
    title: "INFÂNCIA DE JESUS",
    theme: "infancy",
    div: "NOVO TESTAMENTO & APÓCRIFOS CRISTÃOS",
    books: [
      {
        id: "b132",
        num: "132",
        name: "Protevangelico",
        sub: "Proto Evangelho de Tiago (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b133",
        num: "133",
        name: "Evangelho da Natividade de Maria",
        sub: "Evangelho do nascimento de Maria (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b134",
        num: "134",
        name: "Pseudo-Mateus",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b135",
        num: "135",
        name: "Evangelho da Infância de Tomé",
        sub: "Infância de Jesus / Salvador / Pseudo Tomé (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b136",
        num: "136",
        name: "Fragmentos de Tomé",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b137",
        num: "137",
        name: "Evangelho Árabe da Infância",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b138",
        num: "138",
        name: "Evangelho Armênio da Infância",
        sub: "Excertos do Evangelho Armênio (V1)",
        tags: ["v1"],
      },
      {
        id: "b139",
        num: "139",
        name: "História de José, o Carpinteiro",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b140",
        num: "140",
        name: "Cartas de Herodes e Pilatos",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f13",
    num: "13",
    title: "MINISTÉRIO DE JESUS — OS EVANGELHOS",
    theme: "gospels",
    books: [
      {
        id: "b141",
        num: "141",
        name: "Mateus 1–13",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b142",
        num: "142",
        name: "Mateus 14–28",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b143",
        num: "143",
        name: "Marcos",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b144",
        num: "144",
        name: "Evangelho Secreto de Marcos",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b145",
        num: "145",
        name: "Lucas 1–12",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b146",
        num: "146",
        name: "Lucas 13–24",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b147",
        num: "147",
        name: "João 1–12",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b148",
        num: "148",
        name: "João 13–21",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b149",
        num: "149",
        name: "Narrativa da Paixão Pré-Markan",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b150",
        num: "150",
        name: "Epístolas de Jesus e Abgarus",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b151",
        num: "151",
        name: "Evangelho dos Hebreus",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b152",
        num: "152",
        name: "Evangelho dos Ebionitas",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b153",
        num: "153",
        name: "Evangelho dos Nazarenos",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b154",
        num: "154",
        name: "Evangelho de Egerton",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b155",
        num: "155",
        name: "Evangelho de Oxirrinco",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b156",
        num: "156",
        name: "Diálogo do Salvador",
        sub: "Conversações esotéricas pós-ressurreição",
        tags: ["b201", "nag hammadi"],
      },
      {
        id: "b157",
        num: "157",
        name: "Evangelho Segundo Pedro",
        sub: "Evangelho de Pedro (V1/V2)",
        tags: ["b201", "v1", "v2"],
      },
      {
        id: "b158",
        num: "158",
        name: "A Vingança do Salvador",
        sub: "",
        tags: ["b201", "v1"],
      },
    ],
  },
  {
    id: "f14",
    num: "14",
    title: "CICLO DE PILATOS & PÓS-RESSURREIÇÃO",
    theme: "passion",
    books: [
      {
        id: "b159",
        num: "159",
        name: "Evangelho de Nicodemus",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b160",
        num: "160",
        name: "Descida ao Inferno (Grego)",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b161",
        num: "161",
        name: "Descida ao Inferno (Latim)",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b162",
        num: "162",
        name: "Ciclo de Pilatos",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b163",
        num: "163",
        name: "Condenação de Pilatos",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b164",
        num: "164",
        name: "Cartas do Senhor",
        sub: "Carta do Senhor (V1)",
        tags: ["v1"],
      },
      {
        id: "b165",
        num: "165",
        name: "Declarações de José de Arimatéia",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b166",
        num: "166",
        name: "A Narrative de José de Arimatéia",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b167",
        num: "167",
        name: "Discurso Sobre o Domingo",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b168",
        num: "168",
        name: "Apócrifos da Assunção",
        sub: "Trad. da Assunção (V1)",
        tags: ["v1"],
      },
      {
        id: "b169",
        num: "169",
        name: "Passagem da Virgem Maria",
        sub: "Passagem da Bem-Aventurada (V1)",
        tags: ["v1"],
      },
      {
        id: "b170",
        num: "170",
        name: "Agrapha Extra-Evangelho",
        sub: "Ditos não canônicos de Jesus (V1)",
        tags: ["v1"],
      },
      {
        id: "b171",
        num: "171",
        name: "Ressurreição de Cristo (Bartolomeu)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b172",
        num: "172",
        name: "Evangelho de Bartolomeu",
        sub: "",
        tags: ["b201", "v1"],
      },
    ],
  },
  {
    id: "f15",
    num: "15",
    title: "ATOS & MISSÃO APOSTÓLICA",
    theme: "acts",
    books: [
      {
        id: "b173",
        num: "173",
        name: "Atos 1–12",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b174",
        num: "174",
        name: "Atos 13–28",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b175",
        num: "175",
        name: "Atos 29 (Apócrifo)",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b176",
        num: "176",
        name: "Atos de Pedro e os 12",
        sub: "Relato herético da missão dos apóstolos",
        tags: ["b201", "nag hammadi"],
      },
      {
        id: "b177",
        num: "177",
        name: "Atos de Pedro",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b178",
        num: "178",
        name: "Atos de Pedro e André",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b179",
        num: "179",
        name: "Atos de Pedro e Paulo",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b180",
        num: "180",
        name: "Atos de Paulo e Tecla",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b181",
        num: "181",
        name: "Atos de André",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b182",
        num: "182",
        name: "Atos de André e Matias",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b183",
        num: "183",
        name: "Atos de João",
        sub: "Contém traços gnósticos antigos sobre o corpo espiritual de Jesus",
        tags: ["v3"],
      },
      {
        id: "b184",
        num: "184",
        name: "Atos de Tomé",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b185",
        num: "185",
        name: "Consumação de Tomé",
        sub: "A consumação do apóstolo Tomé (V3)",
        tags: ["v3"],
      },
      {
        id: "b186",
        num: "186",
        name: "Atos de Barnabé",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b187",
        num: "187",
        name: "Atos e Martírio de São Mateus",
        sub: "Atos e Martírio do Apóstolo (V3)",
        tags: ["v3"],
      },
      {
        id: "b188",
        num: "188",
        name: "Martírio de Mateus",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b189",
        num: "189",
        name: "Xantipe, Polixena e Rebeca",
        sub: "Vida das Santas Mulheres",
        tags: ["v3"],
      },
      {
        id: "b190",
        num: "190",
        name: "Atos do Santo Apóstolo",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b191",
        num: "191",
        name: "Ensino de Tadeu",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b192",
        num: "192",
        name: "Livro de João Evangelista",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b193",
        num: "193",
        name: "Atos de Perpétua e Felicidade",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b194",
        num: "194",
        name: "A Pregação de Pedro",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f16",
    num: "16",
    title: "CARTAS DE PAULO",
    theme: "epistles",
    books: [
      {
        id: "b195",
        num: "195",
        name: "Gálatas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b196",
        num: "196",
        name: "1 Tessalonicenses",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b197",
        num: "197",
        name: "2 Tessalonicenses",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b198",
        num: "198",
        name: "1 Coríntios",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b199",
        num: "199",
        name: "2 Coríntios",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b200",
        num: "200",
        name: "III Coríntios",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b201",
        num: "201",
        name: "Romanos",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b202",
        num: "202",
        name: "Filipenses",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b203",
        num: "203",
        name: "Colossenses",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b204",
        num: "204",
        name: "Filemão",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b205",
        num: "205",
        name: "Efésios",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b206",
        num: "206",
        name: "1 Timóteo",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b207",
        num: "207",
        name: "2 Timóteo",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      { id: "b208", num: "208", name: "Tito", sub: "", tags: ["b201", "cnbb"] },
      {
        id: "b209",
        num: "209",
        name: "Hebreus",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b210",
        num: "210",
        name: "Laodicenses",
        sub: "Epístola aos Laodicenses (V3)",
        tags: ["b201", "v3"],
      },
      {
        id: "b211",
        num: "211",
        name: "Epístolas a Sêneca",
        sub: "Correspondência entre Paulo e Sêneca (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b212",
        num: "212",
        name: "Prece de Paulo",
        sub: "Oração esotérica de abertura do Codex Jung",
        tags: ["v3", "nag hammadi"],
      },
    ],
  },
  {
    id: "f17",
    num: "17",
    title: "CARTAS GERAIS, APOCALIPSES & REVELAÇÃO",
    theme: "apocalypse",
    books: [
      {
        id: "b213",
        num: "213",
        name: "Tiago",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b214",
        num: "214",
        name: "1 Pedro",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b215",
        num: "215",
        name: "2 Pedro",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b216",
        num: "216",
        name: "1 João",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b217",
        num: "217",
        name: "2 João",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b218",
        num: "218",
        name: "3 João",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b219",
        num: "219",
        name: "Judas",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b220",
        num: "220",
        name: "Epístola dos Apóstolos",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b221",
        num: "221",
        name: "Carta de Pedro à Felipe",
        sub: "Carta e revelação gnóstica pós-ressurreição",
        tags: ["v3", "nag hammadi"],
      },
      {
        id: "b222",
        num: "222",
        name: "Epístola de Barnabé",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b223",
        num: "223",
        name: "Revelação (Apocalipse) 1–11",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b224",
        num: "224",
        name: "Revelação 12–22",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b225",
        num: "225",
        name: "João o Teólogo",
        sub: "A Revelação de São João, o Teólogo (V3)",
        tags: ["v3"],
      },
      {
        id: "b226",
        num: "226",
        name: "Apocalipse de Pedro",
        sub: "Visão mística da crucificação espiritual",
        tags: ["v1", "nag hammadi"],
      },
      {
        id: "b227",
        num: "227",
        name: "Apocalipse de Paulo",
        sub: "Ascensão do apóstolo através dos céus arcontônticos",
        tags: ["v3", "nag hammadi"],
      },
      {
        id: "b228",
        num: "228",
        name: "Apocalipse de Baruch",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b229",
        num: "229",
        name: "Apocalipse de Elias",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b230",
        num: "230",
        name: "Apocalipse de Tomé",
        sub: "Revelação de Tomé (V1)",
        tags: ["v1"],
      },
    ],
  },
  {
    id: "f18",
    num: "18",
    title: "PAIS DA IGREJA & TEXTOS APOSTÓLICOS",
    theme: "fathers",
    books: [
      { id: "b231", num: "231", name: "O Didachê", sub: "", tags: ["b201"] },
      {
        id: "b232",
        num: "232",
        name: "Pastor de Hermas",
        sub: "Livros I (Visões), II (Mandatos) e III (Similitudes) (V2)",
        tags: ["v2"],
      },
      {
        id: "b233",
        num: "233",
        name: "1 Clemente",
        sub: "Primeira Epístola de Clemente aos Coríntios (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b234",
        num: "234",
        name: "2 Clemente",
        sub: "Segunda Epístola de Clemente aos Coríntios (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b235",
        num: "235",
        name: "Apócrifo de Tiago",
        sub: "Ensinamentos secretos de Jesus a Tiago",
        tags: ["b201", "v3", "nag hammadi"],
      },
      {
        id: "b236",
        num: "236",
        name: "Inácio de Antioquia",
        sub: "Efésios, Magnésios, Trales, Romanos, Filadelfianos, Esmirniotas e Policarpo (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b237",
        num: "237",
        name: "Policarpo aos Filipenses",
        sub: "Epístola de Policarpo aos Filipenses (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b238",
        num: "238",
        name: "Martírio de Inácio",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b239",
        num: "239",
        name: "Martírio de Policarpo",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b240",
        num: "240",
        name: "Tertuliano (Mártires)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b241",
        num: "241",
        name: "Carta de Pilatos",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b242",
        num: "242",
        name: "Oração Ação de Graças",
        sub: "Oração esotérica de matriz hermético-gnóstica",
        tags: ["b201", "nag hammadi"],
      },
      {
        id: "b243",
        num: "243",
        name: "Epifânio sobre a Justiça",
        sub: "",
        tags: ["b201"],
      },
      { id: "b244", num: "244", name: "Credos", sub: "", tags: ["b201"] },
    ],
  },
  {
    id: "f19",
    num: "19",
    title: "GNOSE & TEXTOS ESOTÉRICOS",
    theme: "gnosis",
    div: "TEXTOS GNÓSTICOS",
    books: [
      {
        id: "b245",
        num: "245",
        name: "Evangelho de Tomé",
        sub: "Evangelho Segundo Tomé, o Dídimo (V1)",
        tags: ["b201", "v1", "gnose", "nag hammadi"],
      },
      {
        id: "b246",
        num: "246",
        name: "Fragmentos Gregos de Tomé",
        sub: "Versões em papiro de Oxirrinco",
        tags: ["b201", "gnose"],
      },
      {
        id: "b247",
        num: "247",
        name: "Evangelho de Filipe",
        sub: "Evangelho Segundo Felipe (V1)",
        tags: ["b201", "v1", "gnose", "nag hammadi"],
      },
      {
        id: "b248",
        num: "248",
        name: "Evangelho de Maria Madalena",
        sub: "Gnose mística a partir do Codex de Berlim",
        tags: ["v1", "gnose"],
      },
      {
        id: "b248b",
        num: "248b",
        name: "Excertos do Evangelho de Maria",
        sub: "(V1)",
        tags: ["v1", "gnose"],
      },
      {
        id: "b249",
        num: "249",
        name: "Evangelho de Judas",
        sub: "Tradição Gnóstica Cainita a partir do Codex Tchacos",
        tags: ["v1", "gnose"],
      },
      {
        id: "b250",
        num: "250",
        name: "Evangelho de Valentino",
        sub: "Expressão maior da gnose valentiniana poética",
        tags: ["v1", "gnose"],
      },
      {
        id: "b251",
        num: "251",
        name: "Evangelho da Verdade",
        sub: "Tratado profundo atribuído a Valentino",
        tags: ["b201", "v1", "gnose", "nag hammadi"],
      },
      {
        id: "b252",
        num: "252",
        name: "Evangelho dos Egípcios",
        sub: "O Livro Sagrado do Grande Espírito Invisível",
        tags: ["b201", "gnose", "nag hammadi"],
      },
      {
        id: "b253",
        num: "253",
        name: "Apócrifo de João",
        sub: "O Livro Secreto de João e a cosmologia da Luz",
        tags: ["b201", "v3", "gnose", "nag hammadi"],
      },
      {
        id: "b254",
        num: "254",
        name: "Thomas Contendor",
        sub: "Livro de Tomé o Contendor (V3)",
        tags: ["b201", "v3", "gnose", "nag hammadi"],
      },
      {
        id: "b255",
        num: "255",
        name: "Tratado Grande Seth",
        sub: "Revelação da linhagem celestial e do Cristo espiritual",
        tags: ["b201", "gnose", "nag hammadi"],
      },
      {
        id: "b256",
        num: "256",
        name: "Basilides",
        sub: "Fragmentos heresiológicos",
        tags: ["b201", "gnose"],
      },
      {
        id: "b257",
        num: "257",
        name: "Livro de Marcião",
        sub: "O Evangelho do Deus Estrangeiro",
        tags: ["b201", "gnose"],
      },
      {
        id: "b258",
        num: "258",
        name: "Livro de Sindos",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b259",
        num: "259",
        name: "Fonte Q",
        sub: "Reconstrução hipotética dos ditos originais",
        tags: ["b201", "gnose"],
      },
      {
        id: "b260",
        num: "260",
        name: "Pistis Sophia Comentada",
        sub: "Samael Aun Weor — O código-fonte da gnose com chaves interpretativas profundas",
        tags: ["gnose", "esoterismo", "carrinho"],
      },
      {
        id: "b261",
        num: "261",
        name: "Evangelho Nestoriano",
        sub: "José Alves de Araújo Filho — O livro dos ensinamentos alternativos do Oriente",
        tags: ["gnose", "carrinho"],
      },
      {
        id: "b262",
        num: "262",
        name: "Trovão: Mente Perfeita",
        sub: "Poema revelatório de voz feminina divina (V1)",
        tags: ["v1", "gnose", "nag hammadi"],
      },
      {
        id: "b263",
        num: "263",
        name: "Hipóstase dos Arcontes",
        sub: "Natureza e origem dos arcontes — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b264",
        num: "264",
        name: "Protennoia Trimórfica",
        sub: "Três descidas do Primeiro Pensamento divino (V1)",
        tags: ["v1", "gnose", "nag hammadi"],
      },
      {
        id: "b265",
        num: "265",
        name: "Tratado Tripartite",
        sub: "Cosmologia valentiniana — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b266",
        num: "266",
        name: "Exegese sobre a Alma",
        sub: "Alegoria mística da queda e resgate da alma humana",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b267",
        num: "267",
        name: "Sofia de Jesus Cristo",
        sub: "Versão gnóstica do Eugnostos — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b268",
        num: "268",
        name: "Testemunho da Verdade",
        sub: "Crítica radical ao martírio e ao Criador material",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b269",
        num: "269",
        name: "Zostrianos",
        sub: "Apocalipse sethiano — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b269_add1",
        num: "269b",
        name: "As Três Estelas de Sete",
        sub: "Hinos de adoração e revelações da linhagem sethiana pura",
        tags: ["gnose", "sethiano", "nag hammadi"],
      },
      {
        id: "b269_add2",
        num: "269c",
        name: "O Alógenes",
        sub: "O Estrangeiro e sua transcendência mental além do Demiurgo",
        tags: ["gnose", "revelacao", "nag hammadi"],
      },
    ],
  },
  {
    id: "f20",
    num: "20",
    title: "GNOSE COMO PONTE",
    theme: "bridge",
    div: "TRANSIÇÃO ISLÃ",
    books: [
      {
        id: "b270",
        num: "270",
        name: "Gnósticos: Escrituras apócrifas Setianas",
        sub: "José Alves de Araújo Filho — Análise focada na linhagem herética de Sete",
        tags: ["gnose", "ponte", "carrinho"],
      },
      {
        id: "b271",
        num: "271",
        name: "Ele Não Morreu na Cruz",
        sub: "José Alves de Araújo Filho — O relato revisionista sobre a crucificação e sobrevivência física",
        tags: ["ponte", "revisionismo", "carrinho"],
      },
      {
        id: "b272",
        num: "272",
        name: "O Famigerado Apóstolo Paulo: O Maior deturpador do Cristianismo",
        sub: "José Alves de Araújo Filho — Crítica estrutural à formação do dogma romano ortodoxo",
        tags: ["ponte", "critica", "carrinho"],
      },
      {
        id: "b273",
        num: "273",
        name: "EUTAOGNOSE: A Religião dos Anjos",
        sub: "José Alves de Araújo Filho — Cosmologia e hierarquias intermediárias na transição doutrinária",
        tags: ["ponte", "misticismo", "carrinho"],
      },
      {
        id: "b273_comp",
        num: "273b",
        name: "O grande arcano ou o occultismo revelado",
        sub: "Éliphas Lévi — A manipulação analítica da luz astral e o fechamento do entendimento do sistema ocidental",
        tags: ["ocultismo", "síntese", "carrinho"],
      },
    ],
  },
  {
    id: "f21",
    num: "21",
    title: "A REVELAÇÃO DE MAOMÉ",
    theme: "islam",
    books: [
      {
        id: "b274",
        num: "274",
        name: "O Evangelho de Barnabé: O Gospel Apócrifo de Barnabé",
        sub: "José Alves de Araújo Filho — Visão de transição doutrinária que aproxima a figura profética ao Islã",
        tags: ["ponte", "apocrifo", "carrinho"],
      },
      {
        id: "b275",
        num: "275",
        name: "O ALCORÃO",
        sub: "",
        tags: ["ponte"],
      },
      {
        id: "b276",
        num: "276",
        name: "Sirah Nabawi",
        sub: "Biografia do Profeta Muhammad — Ibn Hisham",
        tags: ["missing", "ponte"],
      },
    ],
  },
];

export const CANON_DATA_ENGLISH: Phase[] = [
  {
    id: "f0",
    num: "0",
    title: "FOUNDATIONS & HERMETIC KEYS",
    theme: "hermetism_base",
    div: "PRELIMINARY STUDIES — READING KEYS",
    books: [
      {
        id: "b0_1",
        num: "0a",
        name: "Corpus Hermeticum Græcum",
        sub: "Trans. David Pessoa de Lira — Philosophy of the origin of consciousness and the Word",
        tags: ["hermetismo", "base", "carrinho"],
      },
      {
        id: "b0_2",
        num: "0b",
        name: "The Emerald Tablet",
        sub: "Trans. Fabio R. de Araujo — The secret laws of analogy and correspondence",
        tags: ["alquimia", "base", "carrinho"],
      },
      {
        id: "b0_3",
        num: "0c",
        name: "History of Magic",
        sub: "Éliphas Lévi — Historical panorama of the evolution of occult thought in humanity",
        tags: ["ocultismo", "historia", "carrinho"],
      },
      {
        id: "b0_4",
        num: "0d",
        name: "The Kabbalah: Secret Tradition of the West",
        sub: "Papus — The theoretical and cosmogonic structure of the Tree of Life",
        tags: ["cabala", "base", "carrinho"],
      },
      {
        id: "b0_5",
        num: "0e",
        name: "Transcendental Magic, Its Doctrine and Ritual",
        sub: "Éliphas Lévi — The absolute compendium of correspondences and the laws of the applied will",
        tags: ["ocultismo", "teoria", "carrinho"],
      },
      {
        id: "b0_6",
        num: "0f",
        name: "The Key to the Great Mysteries",
        sub: "Éliphas Lévi — Symbolic keys and the reconciliation between science and religion",
        tags: ["ocultismo", "teoria", "carrinho"],
      },
      {
        id: "b0_7",
        num: "0g",
        name: "Introduction to Hermetic Science",
        sub: "Giuliano Kremmerz — The initiatory path and the laws of natural magic",
        tags: ["hermetismo", "pratica", "carrinho"],
      },
      {
        id: "b0_8",
        num: "0h",
        name: "The Kybalion",
        sub: "Three Initiates — The seven hermetic principles that govern the hidden truth and the laws of the mind",
        tags: ["hermetismo", "base", "carrinho"],
      },
    ],
  },
  {
    id: "f1",
    num: "1",
    title: "CREATION & ORIGINS",
    theme: "genesis",
    books: [
      {
        id: "b1",
        num: "1",
        name: "Genesis 1–5",
        sub: "Creation, Adam and Eve, Cain and Abel, genealogy",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b1_comp",
        num: "1b",
        name: "Demiurgos: On the Creation of Worlds",
        sub: "Juliano C. S. Neves — The philosophical and gnostic counterpoint of the material creation process",
        tags: ["gnose", "cosmogonia", "carrinho"],
      },
      {
        id: "b2",
        num: "2",
        name: "Adam and Eve I",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b3",
        num: "3",
        name: "Adam and Eve II",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b4",
        num: "4",
        name: "Adam and Eve III",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b5",
        num: "5",
        name: "Vita Adae et Evae",
        sub: "Latin version",
        tags: ["b201"],
      },
      {
        id: "b6",
        num: "6",
        name: "Slavonic Vita Adae et Evae",
        sub: "Slavonic version",
        tags: ["b201"],
      },
      {
        id: "b7",
        num: "7",
        name: "Book of Adam",
        sub: "The Conflict of Adam and Eve with Satan (V1)",
        tags: ["v3"],
      },
      {
        id: "b7b",
        num: "7b",
        name: "Testament of Adam",
        sub: "(V1)",
        tags: ["v3"],
      },
      {
        id: "b7c",
        num: "7c",
        name: "Apocalypse of Adam",
        sub: "",
        tags: ["b201", "v1", "nag hammadi"],
      },
      {
        id: "b8",
        num: "8",
        name: "Genesis 6–11",
        sub: "Watchers, Noah, the Flood, Tower of Babel",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b9",
        num: "9",
        name: "Flood Narrative — Epic of Gilgamesh",
        sub: "Mesopotamian parallel to the biblical flood",
        tags: ["v1"],
      },
      {
        id: "b10",
        num: "10",
        name: "1 Enoch",
        sub: "Watchers, Parables, Astronomy, Dreams, Epistle",
        tags: ["b201", "v1"],
      },
      {
        id: "b11",
        num: "11",
        name: "2 Enoch",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b12",
        num: "12",
        name: "3 Enoch",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b12b",
        num: "12b",
        name: "The Book of the Secrets of Enoch (V1)",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b13",
        num: "13",
        name: "The Book of Giants",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f2",
    num: "2",
    title: "PATRIARCHS & JUBILEES",
    theme: "patriarchs",
    books: [
      {
        id: "b14",
        num: "14",
        name: "Genesis 12–25",
        sub: "Abraham, Lot, Isaac, covenant",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b14_comp",
        num: "14b",
        name: "Practical Kabbalah Without Mysteries",
        sub: "Maggy Whitehouse — Analytical application of the Patriarchs' archetypes on the Tree",
        tags: ["cabala", "analise", "carrinho"],
      },
      {
        id: "b15",
        num: "15",
        name: "Jubilees",
        sub: "Rewriting of Genesis with calendar and angels",
        tags: ["b201", "v1"],
      },
      {
        id: "b16",
        num: "16",
        name: "Testament of Abraham",
        sub: "The death and judgment of the patriarch's soul",
        tags: ["b201", "v1"],
      },
      {
        id: "b17",
        num: "17",
        name: "Apocalypse of Abraham",
        sub: "Heavenly vision and conversion",
        tags: ["v1"],
      },
      {
        id: "b18",
        num: "18",
        name: "Book of Abraham",
        sub: "Expanded version of Abrahamic traditions",
        tags: ["v3"],
      },
      {
        id: "b19",
        num: "19",
        name: "Cave of Treasures",
        sub: "Syriac tradition of patriarchal stories (V1)",
        tags: ["v1"],
      },
      {
        id: "b20",
        num: "20",
        name: "Tale of the Patriarchs",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b21",
        num: "21",
        name: "Genesis 26–36",
        sub: "Isaac, Jacob, Esau",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b22",
        num: "22",
        name: "Final Testaments of the 12 Patriarchs (Later Tradition)",
        sub: "Introduction to the last words of Jacob's sons",
        tags: ["b201", "v1"],
      },
      {
        id: "b23",
        num: "23",
        name: "Testament of Reuben",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b24",
        num: "24",
        name: "Testament of Simeon",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b25",
        num: "25",
        name: "Testament of Levi",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b26",
        num: "26",
        name: "Testament of Judah",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b27",
        num: "27",
        name: "Testament of Issachar",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b28",
        num: "28",
        name: "Testament of Zebulun",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b29",
        num: "29",
        name: "Testament of Dan",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b30",
        num: "30",
        name: "Testament of Naphtali",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b31",
        num: "31",
        name: "Testament of Gad",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b32",
        num: "32",
        name: "Testament of Asher",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b33",
        num: "33",
        name: "Testament of Joseph",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b34",
        num: "34",
        name: "Testament of Benjamin",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b35",
        num: "35",
        name: "Genesis 37–50",
        sub: "Joseph in Egypt",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b36",
        num: "36",
        name: "Joseph and Asenath",
        sub: "Novel about Joseph's marriage",
        tags: ["v1"],
      },
      {
        id: "b37",
        num: "37",
        name: "Book of Jasher",
        sub: "Mentioned in Joshua and 2 Samuel",
        tags: ["v2"],
      },
      {
        id: "b38",
        num: "38",
        name: "Escada de Jacó",
        sub: "Expansão do sonho de Jacó em Betel",
        tags: ["missing"],
      },
      {
        id: "b39",
        num: "39",
        name: "Testamento de Jó",
        sub: "Expansão apócrifa da história de Jó",
        tags: ["missing"],
      },
      {
        id: "b40",
        num: "40",
        name: "Pseudo-Filo — Antiguidades Bíblicas",
        sub: "Reescrita de Adão a Saul",
        tags: ["missing"],
      },
    ],
  },
  {
    id: "f3",
    num: "3",
    title: "TEXT REMOVED FOR DUPLICITY CORRECTION — EXODUS & THE LAW",
    theme: "exodus",
    books: [
      {
        id: "b41",
        num: "41",
        name: "Exodus",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b42",
        num: "42",
        name: "Jannes and Jambres",
        sub: "The magicians of Pharaoh",
        tags: ["b201"],
      },
      {
        id: "b43",
        num: "43",
        name: "Leviticus",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b44",
        num: "44",
        name: "Numbers",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b45",
        num: "45",
        name: "Deuteronomy",
        sub: "The Shema and the synthesis of the Law",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b46",
        num: "46",
        name: "Testament of Moses",
        sub: "Assumption of Moses (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b47",
        num: "47",
        name: "Apocalypse of Moses",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b48",
        num: "48",
        name: "Selections from the Book of Moses",
        sub: "Intertestamental tradition (V3)",
        tags: ["v3"],
      },
      {
        id: "b49",
        num: "49",
        name: "Fragments of a Zadokite Work",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b50",
        num: "50",
        name: "Damascus Document",
        sub: "Dead Sea Scrolls",
        tags: ["v3"],
      },
    ],
  },
  {
    id: "f4",
    num: "4",
    title: "DEAD SEA SCROLLS",
    theme: "qumran",
    books: [
      {
        id: "b51",
        num: "51",
        name: "Community Rule (1QS)",
        sub: "Serek ha-Yahad — community rules of Qumran",
        tags: ["missing"],
      },
      {
        id: "b52",
        num: "52",
        name: "War Scroll (1QM)",
        sub: "Milhamah — war of the sons of light against the sons of darkness",
        tags: ["missing"],
      },
      {
        id: "b53",
        num: "53",
        name: "Thanksgiving Hymns (1QH)",
        sub: "Hodayot — hymns of thanksgiving",
        tags: ["missing"],
      },
      {
        id: "b54",
        num: "54",
        name: "Temple Scroll (11QT)",
        sub: "The longest Qumran manuscript — Temple law and architecture",
        tags: ["missing"],
      },
      {
        id: "b55",
        num: "55",
        name: "Genesis Apocryphon (1QapGen)",
        sub: "Narrative expansion of Genesis 1–15",
        tags: ["missing"],
      },
    ],
  },
  {
    id: "f5",
    num: "5",
    title: "CONQUEST & JUDGES",
    theme: "conquest_and_judges",
    books: [
      {
        id: "b56",
        num: "56",
        name: "Joshua",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b57",
        num: "57",
        name: "Judges",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b58",
        num: "58",
        name: "Ruth",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b59",
        num: "59",
        name: "The Story of Ahikar",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b60",
        num: "60",
        name: "Eldad and Modad",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b61",
        num: "61",
        name: "Melchizedek",
        sub: "Priest-king of Salem",
        tags: ["v1"],
      },
    ],
  },
  {
    id: "f6",
    num: "6",
    title: "KINGDOM OF ISRAEL & ATTRIBUTED TRADITIONS",
    theme: "kingdom",
    books: [
      {
        id: "b62",
        num: "62",
        name: "1 Samuel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b63",
        num: "63",
        name: "2 Samuel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b64",
        num: "64",
        name: "1 Kings",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b65",
        num: "65",
        name: "2 Kings",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b66",
        num: "66",
        name: "1 Chronicles",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b67",
        num: "67",
        name: "2 Chronicles",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b68",
        num: "68",
        name: "Testament of Solomon",
        sub: "On demons and the Temple",
        tags: ["missing"],
      },
      {
        id: "b68_grim1",
        num: "68b",
        name: "The Key of Solomon",
        sub: "S. L. MacGregor Mathers — Analytical-textual study of the medieval ritual manual attributed to Solomon",
        tags: ["grimorio", "solomon", "carrinho"],
      },
      {
        id: "b68_grim2",
        num: "68c",
        name: "Goetia",
        sub: "Humberto Maggi — Study of the keys of evocation and symbolic control of the 72 spirits",
        tags: ["grimorio", "goetia", "carrinho"],
      },
      {
        id: "b68_grim3",
        num: "68d",
        name: "Grimorium Verum",
        sub: "Frater Goya (Anderson Rosa) — Technical analysis of the currents and hierarchies of the Solomonic tradition",
        tags: ["grimorio", "pratica", "carrinho"],
      },
    ],
  },
  {
    id: "f7",
    num: "7",
    title: "EXILE, RETURN & DEUTEROCANONICALS",
    theme: "exile",
    books: [
      {
        id: "b69",
        num: "69",
        name: "1 Esdras",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b70",
        num: "70",
        name: "2 Esdras",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b71",
        num: "71",
        name: "4 Ezra",
        sub: "(Revelation)",
        tags: ["v3"],
      },
      {
        id: "b71b",
        num: "71b",
        name: "Word and Revelation of Ezra",
        sub: "The Holy Prophet and Beloved of God (V3)",
        tags: ["v3"],
      },
      {
        id: "b72",
        num: "72",
        name: "Nehemiah",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b73",
        num: "73",
        name: "Letter of Aristeas",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b74",
        num: "74",
        name: "Tobit",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b75",
        num: "75",
        name: "Judith",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b76",
        num: "76",
        name: "Esther + Additions to Esther",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b77",
        num: "77",
        name: "Susanna",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b78",
        num: "78",
        name: "Bel and the Dragon",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b79",
        num: "79",
        name: "1 Maccabees",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b80",
        num: "80",
        name: "2 Maccabees",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b81",
        num: "81",
        name: "3 Maccabees",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b82",
        num: "82",
        name: "4 Maccabees",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b83",
        num: "83",
        name: "1 Meqabyan",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b84",
        num: "84",
        name: "2 Meqabyan",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b85",
        num: "85",
        name: "3 Meqabyan",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b86",
        num: "86",
        name: "Wisdom of Solomon",
        sub: "Deuterocanonical wisdom attributed to Solomon",
        tags: ["missing", "cnbb"],
      },
    ],
  },
  {
    id: "f8",
    num: "8",
    title: "WISDOM & POETRY",
    theme: "wisdom",
    books: [
      {
        id: "b87",
        num: "87",
        name: "Job",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b88",
        num: "88",
        name: "Psalms 1–72",
        sub: "Books I and II",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b89",
        num: "89",
        name: "Psalms 73–150",
        sub: "Books III, IV and V",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b89_comp",
        num: "89b",
        name: "The Book of Splendours",
        sub: "Éliphas Lévi — The hieratic mystery and the western kabbalistic interpretation of the psalms and traditional secrets",
        tags: ["cabala", "esoterismo", "carrinho"],
      },
      {
        id: "b90",
        num: "90",
        name: "Psalms of Solomon",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b91",
        num: "91",
        name: "Additional Psalms",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b92",
        num: "92",
        name: "Odes of Solomon",
        sub: "",
        tags: ["b201", "v2"],
      },
      {
        id: "b93",
        num: "93",
        name: "Hymn of the Pearl",
        sub: "Gnostic poem (V1)",
        tags: ["v1", "gnose"],
      },
      {
        id: "b94",
        num: "94",
        name: "Proverbs",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b95",
        num: "95",
        name: "Ecclesiastes",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b96",
        num: "96",
        name: "Song of Songs",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b97",
        num: "97",
        name: "Sirach (Ecclesiasticus)",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b98",
        num: "98",
        name: "On the Origin of the World",
        sub: "Gnostic tradition (V1)",
        tags: ["v1", "gnose", "nag hammadi"],
      },
      {
        id: "b99",
        num: "99",
        name: "The Sentences of Sextus",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b100",
        num: "100",
        name: "The Traditions of Matthias",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f9",
    num: "9",
    title: "MAJOR PROPHETS",
    theme: "prophets",
    books: [
      {
        id: "b101",
        num: "101",
        name: "Isaiah 1–39",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b102",
        num: "102",
        name: "Isaiah 40–66",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b102_comp",
        num: "102b",
        name: "The Magus: A Complete System of Occult Philosophy",
        sub: "Francis Barrett — Classic synthesis encyclopedia; excellent parallel for the analytical study of the prophetic and astrological period",
        tags: ["ocultismo", "enciclopedia", "carrinho"],
      },
      {
        id: "b103",
        num: "103",
        name: "Ascension of Isaiah",
        sub: "(V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b103b",
        num: "103b",
        name: "Martyrdom of Isaiah",
        sub: "(V1)",
        tags: ["v1"],
      },
      {
        id: "b104",
        num: "104",
        name: "Jeremiah",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b105",
        num: "105",
        name: "Letter of Jeremiah",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b106",
        num: "106",
        name: "Lamentations",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b107",
        num: "107",
        name: "Baruch 1 · 2 · 3",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b108",
        num: "108",
        name: "Prayer of Azariah",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b109",
        num: "109",
        name: "Ezekiel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b110",
        num: "110",
        name: "Daniel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b111",
        num: "111",
        name: "4 Baruch (Paraleipomena Jeremiou)",
        sub: "Apocryphal expansion of Jeremiah and Baruch",
        tags: ["missing"],
      },
      {
        id: "b112",
        num: "112",
        name: "Lives of the Prophets",
        sub: "Biographical traditions of OT prophets",
        tags: ["missing"],
      },
    ],
  },
  {
    id: "f10",
    num: "10",
    title: "MINOR PROPHETS & ORACLES",
    theme: "minor_prophets",
    books: [
      {
        id: "b113",
        num: "113",
        name: "Hosea",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b114",
        num: "114",
        name: "Joel",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b115",
        num: "115",
        name: "Amos",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b116",
        num: "116",
        name: "Obadiah",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b117",
        num: "117",
        name: "Jonah",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b118",
        num: "118",
        name: "Micah",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b119",
        num: "119",
        name: "Nahum",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b120",
        num: "120",
        name: "Habakkuk",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b121",
        num: "121",
        name: "Zephaniah",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b122",
        num: "122",
        name: "Haggai",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b123",
        num: "123",
        name: "Zechariah",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b124",
        num: "124",
        name: "Malachi",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b125",
        num: "125",
        name: "Prayer of Manasseh",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b126",
        num: "126",
        name: "Sibylline Oracles I–XIV",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f11",
    num: "11",
    title: "BETWEEN THE TESTAMENTS",
    theme: "intertestamental",
    div: "INTERTESTAMENTAL PERIOD",
    books: [
      {
        id: "b127",
        num: "127",
        name: "The Ascension of Isaiah (Revision)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b128",
        num: "128",
        name: "Testament of Moses (Revision)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b129",
        num: "129",
        name: "Book of Adam (V.3)",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b130",
        num: "130",
        name: "Testament of Isaac",
        sub: "Intertestamental patriarchal tradition",
        tags: ["v1"],
      },
      {
        id: "b131",
        num: "131",
        name: "Testament of Jacob",
        sub: "Intertestamental patriarchal tradition",
        tags: ["v1"],
      },
    ],
  },
  {
    id: "f12",
    num: "12",
    title: "INFANCY OF JESUS",
    theme: "infancy",
    div: "NEW TESTAMENT & CHRISTIAN APOCRYPHA",
    books: [
      {
        id: "b132",
        num: "132",
        name: "Protevangelium",
        sub: "Proto-Gospel of James (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b133",
        num: "133",
        name: "Gospel of the Nativity of Mary",
        sub: "Gospel of the Birth of Mary (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b134",
        num: "134",
        name: "Pseudo-Matthew",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b135",
        num: "135",
        name: "Infancy Gospel of Thomas",
        sub: "Infancy of Jesus / Savior / Pseudo-Thomas (V1)",
        tags: ["b201", "v1"],
      },
      {
        id: "b136",
        num: "136",
        name: "Fragments of Thomas",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b137",
        num: "137",
        name: "Arabic Infancy Gospel",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b138",
        num: "138",
        name: "Armenian Infancy Gospel",
        sub: "Excerpts from the Armenian Gospel (V1)",
        tags: ["v1"],
      },
      {
        id: "b139",
        num: "139",
        name: "History of Joseph the Carpenter",
        sub: "",
        tags: ["b201", "v1"],
      },
      {
        id: "b140",
        num: "140",
        name: "Letters of Herod and Pilate",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f13",
    num: "13",
    title: "MINISTRY OF JESUS — THE GOSPELS",
    theme: "gospels",
    books: [
      {
        id: "b141",
        num: "141",
        name: "Matthew 1–13",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b142",
        num: "142",
        name: "Matthew 14–28",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b143",
        num: "143",
        name: "Mark",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b144",
        num: "144",
        name: "Secret Gospel of Mark",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b145",
        num: "145",
        name: "Luke 1–12",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b146",
        num: "146",
        name: "Luke 13–24",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b147",
        num: "147",
        name: "John 1–12",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b148",
        num: "148",
        name: "John 13–21",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b149",
        num: "149",
        name: "Pre-Markan Passion Narrative",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b150",
        num: "150",
        name: "Epistles of Jesus and Abgarus",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b151",
        num: "151",
        name: "Gospel of the Hebrews",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b152",
        num: "152",
        name: "Gospel of the Ebionites",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b153",
        num: "153",
        name: "Gospel of the Nazarenes",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b154",
        num: "154",
        name: "Egerton Gospel",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b155",
        num: "155",
        name: "Oxyrhynchus Gospel",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b156",
        num: "156",
        name: "Dialogue of the Savior",
        sub: "",
        tags: ["b201", "nag hammadi"],
      },
      {
        id: "b157",
        num: "157",
        name: "Gospel According to Peter",
        sub: "Gospel of Peter (V1/V2)",
        tags: ["b201", "v1", "v2"],
      },
      {
        id: "b158",
        num: "158",
        name: "The Vengeance of the Savior",
        sub: "",
        tags: ["b201", "v1"],
      },
    ],
  },
  {
    id: "f14",
    num: "14",
    title: "PILATE CYCLE & POST-RESURRECTION",
    theme: "passion",
    books: [
      {
        id: "b159",
        num: "159",
        name: "Gospel of Nicodemus",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b160",
        num: "160",
        name: "Descent into Hell (Greek)",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b161",
        num: "161",
        name: "Descent into Hell (Latin)",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b162",
        num: "162",
        name: "Pilate Cycle",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b163",
        num: "163",
        name: "Condemnation of Pilate",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b164",
        num: "164",
        name: "Letters of the Lord",
        sub: "Letter of the Lord (V1)",
        tags: ["v1"],
      },
      {
        id: "b165",
        num: "165",
        name: "Declarations of Joseph of Arimathea",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b166",
        num: "166",
        name: "The Narrative of Joseph of Arimathea",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b167",
        num: "167",
        name: "Discourse on the Lord's Day",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b168",
        num: "168",
        name: "Assumption Apocrypha",
        sub: "Assumption tradition (V1)",
        tags: ["v1"],
      },
      {
        id: "b169",
        num: "169",
        name: "Passing of the Virgin Mary",
        sub: "Passing of the Blessed (V1)",
        tags: ["v1"],
      },
      {
        id: "b170",
        num: "170",
        name: "Extra-Gospel Agrapha",
        sub: "Non-canonical sayings of Jesus (V1)",
        tags: ["v1"],
      },
      {
        id: "b171",
        num: "171",
        name: "Resurrection of Christ (Bartholomew)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b172",
        num: "172",
        name: "Gospel of Bartholomew",
        sub: "",
        tags: ["b201", "v1"],
      },
    ],
  },
  {
    id: "f15",
    num: "15",
    title: "ACTS & APOSTOLIC MISSION",
    theme: "acts",
    books: [
      {
        id: "b173",
        num: "173",
        name: "Acts 1–12",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b174",
        num: "174",
        name: "Acts 13–28",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b175",
        num: "175",
        name: "Acts 29 (Apocryphal)",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b176",
        num: "176",
        name: "Acts of Peter and the Twelve",
        sub: "",
        tags: ["b201", "nag hammadi"],
      },
      {
        id: "b177",
        num: "177",
        name: "Acts of Peter",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b178",
        num: "178",
        name: "Acts of Peter and Andrew",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b179",
        num: "179",
        name: "Acts of Peter and Paul",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b180",
        num: "180",
        name: "Acts of Paul and Thecla",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b181",
        num: "181",
        name: "Acts of Andrew",
        sub: "",
        tags: ["b201", "v3"],
      },
      {
        id: "b182",
        num: "182",
        name: "Acts of Andrew and Matthias",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b183",
        num: "183",
        name: "Acts of John",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b184",
        num: "184",
        name: "Acts of Thomas",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b185",
        num: "185",
        name: "Consummation of Thomas",
        sub: "The consummation of the apostle Thomas (V3)",
        tags: ["v3"],
      },
      {
        id: "b186",
        num: "186",
        name: "Acts of Barnabas",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b187",
        num: "187",
        name: "Acts and Martyrdom of St. Matthew",
        sub: "Acts and Martyrdom of the Apostle (V3)",
        tags: ["v3"],
      },
      {
        id: "b188",
        num: "188",
        name: "Martyrdom of Matthew",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b189",
        num: "189",
        name: "Xanthippe, Polyxena and Rebecca",
        sub: "Life of the Holy Women",
        tags: ["v3"],
      },
      {
        id: "b190",
        num: "190",
        name: "Acts of the Holy Apostle",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b191",
        num: "191",
        name: "Teaching of Thaddaeus",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b192",
        num: "192",
        name: "Book of John the Evangelist",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b193",
        num: "193",
        name: "Acts of Perpetua and Felicity",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b194",
        num: "194",
        name: "The Preaching of Peter",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f16",
    num: "16",
    title: "LETTERS OF PAUL",
    theme: "epistles",
    books: [
      {
        id: "b195",
        num: "195",
        name: "Galatians",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b196",
        num: "196",
        name: "1 Thessalonians",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b197",
        num: "197",
        name: "2 Thessalonians",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b198",
        num: "198",
        name: "1 Corinthians",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b199",
        num: "199",
        name: "2 Corinthians",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b200",
        num: "200",
        name: "3 Corinthians",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b201",
        num: "201",
        name: "Romans",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b202",
        num: "202",
        name: "Philippians",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b203",
        num: "203",
        name: "Colossians",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b204",
        num: "204",
        name: "Philemon",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b205",
        num: "205",
        name: "Ephesians",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b206",
        num: "206",
        name: "1 Timothy",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b207",
        num: "207",
        name: "2 Timothy",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b208",
        num: "208",
        name: "Titus",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b209",
        num: "209",
        name: "Hebrews",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b210",
        num: "210",
        name: "Laodiceans",
        sub: "Epistle to the Laodiceans (V3)",
        tags: ["b201", "v3"],
      },
      {
        id: "b211",
        num: "211",
        name: "Epistles to Seneca",
        sub: "Correspondence between Paul and Seneca (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b212",
        num: "212",
        name: "Prayer of Paul",
        sub: "",
        tags: ["v3", "nag hammadi"],
      },
    ],
  },
  {
    id: "f17",
    num: "17",
    title: "GENERAL LETTERS, APOCALYPSES & REVELATION",
    theme: "apocalypse",
    books: [
      {
        id: "b213",
        num: "213",
        name: "James",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b214",
        num: "214",
        name: "1 Peter",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b215",
        num: "215",
        name: "2 Peter",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b216",
        num: "216",
        name: "1 John",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b217",
        num: "217",
        name: "2 John",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b218",
        num: "218",
        name: "3 John",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b219",
        num: "219",
        name: "Jude",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b220",
        num: "220",
        name: "Epistle of the Apostles",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b221",
        num: "221",
        name: "Letter of Peter to Philip",
        sub: "",
        tags: ["v3", "nag hammadi"],
      },
      {
        id: "b222",
        num: "222",
        name: "Epistle of Barnabas",
        sub: "",
        tags: ["v3"],
      },
      {
        id: "b223",
        num: "223",
        name: "Revelation (Apocalypse) 1–11",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b224",
        num: "224",
        name: "Revelation 12–22",
        sub: "",
        tags: ["b201", "cnbb"],
      },
      {
        id: "b225",
        num: "225",
        name: "John the Theologian",
        sub: "The Revelation of St. John the Theologian (V3)",
        tags: ["v3"],
      },
      {
        id: "b226",
        num: "226",
        name: "Apocalypse of Peter",
        sub: "",
        tags: ["v1", "nag hammadi"],
      },
      {
        id: "b227",
        num: "227",
        name: "Apocalypse of Paul",
        sub: "",
        tags: ["v3", "nag hammadi"],
      },
      {
        id: "b228",
        num: "228",
        name: "Apocalypse of Baruch",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b229",
        num: "229",
        name: "Apocalypse of Elijah",
        sub: "",
        tags: ["v1"],
      },
      {
        id: "b230",
        num: "230",
        name: "Apocalypse of Thomas",
        sub: "Revelation of Thomas (V1)",
        tags: ["v1"],
      },
    ],
  },
  {
    id: "f18",
    num: "18",
    title: "CHURCH FATHERS & APOSTOLIC TEXTS",
    theme: "fathers",
    books: [
      {
        id: "b231",
        num: "231",
        name: "The Didache",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b232",
        num: "232",
        name: "Shepherd of Hermas",
        sub: "Books I (Visions), II (Mandates) and III (Similitudes) (V2)",
        tags: ["v2"],
      },
      {
        id: "b233",
        num: "233",
        name: "1 Clement",
        sub: "First Epistle of Clement to the Corinthians (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b234",
        num: "234",
        name: "2 Clement",
        sub: "Second Epistle of Clement to the Corinthians (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b235",
        num: "235",
        name: "Apocryphon of James",
        sub: "",
        tags: ["b201", "v3", "nag hammadi"],
      },
      {
        id: "b236",
        num: "236",
        name: "Ignatius of Antioch",
        sub: "Ephesians, Magnesians, Trallians, Romans, Philadelphians, Smyrnaeans and Polycarp (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b237",
        num: "237",
        name: "Polycarp to the Philippians",
        sub: "Epistle of Polycarp to the Philippians (V2)",
        tags: ["b201", "v2"],
      },
      {
        id: "b238",
        num: "238",
        name: "Martyrdom of Ignatius",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b239",
        num: "239",
        name: "Martyrdom of Polycarp",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b240",
        num: "240",
        name: "Tertullian (To the Martyrs)",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b241",
        num: "241",
        name: "Letter of Pilate",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b242",
        num: "242",
        name: "Thanksgiving Prayer",
        sub: "",
        tags: ["b201", "nag hammadi"],
      },
      {
        id: "b243",
        num: "243",
        name: "Epiphanes on Righteousness",
        sub: "",
        tags: ["b201"],
      },
      {
        id: "b244",
        num: "244",
        name: "Creeds",
        sub: "",
        tags: ["b201"],
      },
    ],
  },
  {
    id: "f19",
    num: "19",
    title: "GNOSIS & ESOTERIC TEXTS",
    theme: "gnosis",
    div: "GNOSTIC TEXTS",
    books: [
      {
        id: "b245",
        num: "245",
        name: "Gospel of Thomas",
        sub: "Gospel According to Thomas the Twin (V1)",
        tags: ["b201", "v1", "gnose", "nag hammadi"],
      },
      {
        id: "b246",
        num: "246",
        name: "Greek Fragments of Thomas",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b247",
        num: "247",
        name: "Gospel of Philip",
        sub: "Gospel According to Philip (V1)",
        tags: ["b201", "v1", "gnose", "nag hammadi"],
      },
      {
        id: "b248",
        num: "248",
        name: "Gospel of Mary Magdalene",
        sub: "(V1)",
        tags: ["v1", "gnose"],
      },
      {
        id: "b248b",
        num: "248b",
        name: "Excerpts from the Gospel of Mary",
        sub: "(V1)",
        tags: ["v1", "gnose"],
      },
      {
        id: "b249",
        num: "249",
        name: "Gospel of Judas",
        sub: "",
        tags: ["v1", "gnose"],
      },
      {
        id: "b250",
        num: "250",
        name: "Gospel of Valentinus",
        sub: "",
        tags: ["v1", "gnose"],
      },
      {
        id: "b251",
        num: "251",
        name: "Gospel of Truth",
        sub: "",
        tags: ["b201", "v1", "gnose", "nag hammadi"],
      },
      {
        id: "b252",
        num: "252",
        name: "Gospel of the Egyptians",
        sub: "",
        tags: ["b201", "gnose", "nag hammadi"],
      },
      {
        id: "b253",
        num: "253",
        name: "Apocryphon of John",
        sub: "",
        tags: ["b201", "v3", "gnose", "nag hammadi"],
      },
      {
        id: "b254",
        num: "254",
        name: "Thomas the Contender",
        sub: "Book of Thomas the Contender (V3)",
        tags: ["b201", "v3", "gnose", "nag hammadi"],
      },
      {
        id: "b255",
        num: "255",
        name: "Second Treatise of the Great Seth",
        sub: "",
        tags: ["b201", "gnose", "nag hammadi"],
      },
      {
        id: "b256",
        num: "256",
        name: "Basilides",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b257",
        num: "257",
        name: "Book of Marcion",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b258",
        num: "258",
        name: "Book of Sindos",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b259",
        num: "259",
        name: "Q Source",
        sub: "",
        tags: ["b201", "gnose"],
      },
      {
        id: "b260",
        num: "260",
        name: "Pistis Sophia",
        sub: "",
        tags: ["gnose", "esoterismo", "carrinho"],
      },
      {
        id: "b261",
        num: "261",
        name: "Nestorian Gospel",
        sub: "José Alves de Araújo Filho — The book of alternative teachings of the East",
        tags: ["gnose", "carrinho"],
      },
      {
        id: "b262",
        num: "262",
        name: "Thunder: Perfect Mind",
        sub: "Nag Hammadi — poem of a divine female voice (V1)",
        tags: ["v1", "gnose", "nag hammadi"],
      },
      {
        id: "b263",
        num: "263",
        name: "Hypostasis of the Archons",
        sub: "Nature and origin of the archons — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b264",
        num: "264",
        name: "Trimorphic Protennoia",
        sub: "Three descents of the divine Thought — Nag Hammadi (V1)",
        tags: ["v1", "gnose", "nag hammadi"],
      },
      {
        id: "b265",
        num: "265",
        name: "Tripartite Tractate",
        sub: "Valentinian cosmology — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b266",
        num: "266",
        name: "Exegesis on the Soul",
        sub: "Allegory of the fall and redemption of the soul — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b267",
        num: "267",
        name: "Sophia of Jesus Christ",
        sub: "Gnostic version of Eugnostos — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b268",
        num: "268",
        name: "Testimony of Truth",
        sub: "Gnostic critique of martyrdom and the OT God — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b269",
        num: "269",
        name: "Zostrianos",
        sub: "Sethian apocalypse — Nag Hammadi",
        tags: ["gnose", "nag hammadi"],
      },
      {
        id: "b269_add1",
        num: "269b",
        name: "The Three Steles of Seth",
        sub: "Hymns of adoration and revelations of the pure Sethian lineage",
        tags: ["gnose", "sethiano", "nag hammadi"],
      },
      {
        id: "b269_add2",
        num: "269c",
        name: "Allogenes",
        sub: "The Stranger and his mental transcendence beyond the Demiurge",
        tags: ["gnose", "revelacao", "nag hammadi"],
      },
    ],
  },
  {
    id: "f20",
    num: "20",
    title: "GNOSIS AS BRIDGE",
    theme: "bridge",
    div: "TRANSITION TO ISLAM",
    books: [
      {
        id: "b270",
        num: "270",
        name: "Sethian Scriptures",
        sub: "",
        tags: ["gnose", "ponte", "carrinho"],
      },
      {
        id: "b271",
        num: "271",
        name: "He Did Not Die on the Cross",
        sub: "",
        tags: ["ponte", "revisionismo", "carrinho"],
      },
      {
        id: "b272",
        num: "272",
        name: "The Infamous Paul",
        sub: "",
        tags: ["ponte", "critica", "carrinho"],
      },
      {
        id: "b273",
        num: "273",
        name: "EUGNOSTOS",
        sub: "",
        tags: ["ponte", "misticismo", "carrinho"],
      },
      {
        id: "b273_comp",
        num: "273b",
        name: "The Great Secret or Occultism Unveiled",
        sub: "Éliphas Lévi — The analytical manipulation of the astral light and the closing of the understanding of the western system",
        tags: ["ocultismo", "síntese", "carrinho"],
      },
    ],
  },
  {
    id: "f21",
    num: "21",
    title: "MOHAMMED'S REVELATION",
    theme: "islam",
    books: [
      {
        id: "b274",
        num: "274",
        name: "The Gospel of Barnabas: The Apocryphal Gospel of Barnabas",
        sub: "José Alves de Araújo Filho — A doctrinal transition view that brings the prophetic figure closer to Islam",
        tags: ["ponte", "apocrifo", "carrinho"],
      },
      {
        id: "b275",
        num: "275",
        name: "THE QURAN",
        sub: "",
        tags: ["ponte"],
      },
      {
        id: "b276",
        num: "276",
        name: "Sirah Nabawi",
        sub: "Mohammed Biography — Ibn Hisham",
        tags: ["missing", "ponte"],
      },
    ],
  },
];
